.TH "AHFrun.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AHFrun.h \- 
.PP
Header file with all publicly known functions from \fBAHFrun.cpp\fP.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAHFrun\fP (unsigned isnap)"
.br
.RI "\fIControls execution of AHFstep. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Header file with all publicly known functions from \fBAHFrun.cpp\fP. 


.PP
Definition in file \fBAHFrun.h\fP.
.SH "Function Documentation"
.PP 
.SS "void AHFrun (unsigned isnap)"
.PP
Controls execution of AHFstep. Creates the parameter file, invokes AHFstep, moves output files and renames them 
.PP
\fBParameters:\fP
.RS 4
\fIisnap\fP snapshot ID 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 139 of file AHFrun.cpp.
.PP
References CreateAHFParameterFile(), MoveAHFout(), RenameAHFout(), and RunAHFstep().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
