.TH "AOutput.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AOutput.cpp \- 
.PP
rewrite ahf_out_halos for MATLAB input  

.SH SYNOPSIS
.br
.PP
\fC#include 'AOutput.h'\fP
.br
\fC#include 'Output.h'\fP
.br
\fC#include 'Simulation.h'\fP
.br
\fC#include 'Global.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAOutput\fP (int isnap)"
.br
.in -1c
.SH "Detailed Description"
.PP 
rewrite ahf_out_halos for MATLAB input 


.PP
Definition in file \fBAOutput.cpp\fP.
.SH "Function Documentation"
.PP 
.SS "void AOutput (int isnap)"
.PP
Definition at line 32 of file AOutput.cpp.
.PP
References Output::getAR(), Simulation::setIsnap(), and Output::writeAR().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
