.TH "AResults" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AResults \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AResults.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAResults\fP ()"
.br
.ti -1c
.RI "\fBAResults\fP (unsigned npart, unsigned nvpart, float Xc, float Yc, float Zc, float VXc, float VYc, float VZc, float Mvir, float Rvir, float Vmax, float Rmax, float sigV, float lambda, float Jx, float Jy, float Jz, float a, float Eax, float Eay, float Eaz, float b, float Ebx, float Eby, float Ebz, float c, float Ecx, float Ecy, float Ecz, float ovdens, float Redge, int nbins, float Ekin, float Epot, float mbp_offset, float com_offset, float r2, float lambdaE)"
.br
.ti -1c
.RI "\fB~AResults\fP ()"
.br
.ti -1c
.RI "std::string \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file AResults.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AResults::AResults ()"
.PP
Definition at line 32 of file AResults.cpp.
.SS "AResults::AResults (unsigned npart, unsigned nvpart, float Xc, float Yc, float Zc, float VXc, float VYc, float VZc, float Mvir, float Rvir, float Vmax, float Rmax, float sigV, float lambda, float Jx, float Jy, float Jz, float a, float Eax, float Eay, float Eaz, float b, float Ebx, float Eby, float Ebz, float c, float Ecx, float Ecy, float Ecz, float ovdens, float Redge, int nbins, float Ekin, float Epot, float mbp_offset, float com_offset, float r2, float lambdaE)"
.PP
Definition at line 36 of file AResults.cpp.
.SS "AResults::~AResults ()"
.PP
Definition at line 75 of file AResults.cpp.
.SH "Member Function Documentation"
.PP 
.SS "std::string AResults::toString ()"
.PP
Definition at line 80 of file AResults.cpp.
.PP
References Eigensystem3::toString(), and Vector3::toString().

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
