.TH "AResults.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AResults.cpp \- 
.PP
implementation of AHF results storage class  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'AResults.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br
\fC#include 'Eigensystem3.h'\fP
.br

.SH "Detailed Description"
.PP 
implementation of AHF results storage class 


.PP
Definition in file \fBAResults.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
