.TH "Array3.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Array3.h \- 
.PP
a threedimensional array (x,y,z)  

.SH SYNOPSIS
.br
.PP
\fC#include 'Global.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBArray3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a threedimensional array (x,y,z) 


.PP
Definition in file \fBArray3.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
