.TH "Array3.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Array3.cpp \- 
.PP
threedimensional array  

.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Array3.h'\fP
.br

.SH "Detailed Description"
.PP 
threedimensional array 


.PP
Definition in file \fBArray3.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
