.TH "CrossProductWrongDimension" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrossProductWrongDimension \- 
.PP
Exception: Wrong dimension (n!=3) in cross product computatoin This exception is called whenever a vector has a wrong dimension when it should be used in a cross product computation.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossProductWrongDimension\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception: Wrong dimension (n!=3) in cross product computatoin This exception is called whenever a vector has a wrong dimension when it should be used in a cross product computation. 
.PP
Definition at line 60 of file Exceptions.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CrossProductWrongDimension::CrossProductWrongDimension ()\fC [inline]\fP"
.PP
Definition at line 62 of file Exceptions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
