.TH "Distance.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Distance.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Global.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDistance\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
