.TH "Eigensystem3.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Eigensystem3.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Global.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br
\fC#include 'Matrix33.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBEigensystem3\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
