.TH "Eigensystem3.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Eigensystem3.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Global.h'\fP
.br
\fC#include 'Eigensystem3.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
