.TH "ErrNoHalosFound" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrNoHalosFound \- 
.PP
Exception: No halo distribution computed or found This exception is called if operations are attempted on the halo distribution, but no such halo distribution has been calculated (through FindHalos()) or loaded (not yet available).  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrNoHalosFound\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception: No halo distribution computed or found This exception is called if operations are attempted on the halo distribution, but no such halo distribution has been calculated (through FindHalos()) or loaded (not yet available). 
.PP
Definition at line 37 of file Exceptions.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ErrNoHalosFound::ErrNoHalosFound ()\fC [inline]\fP"
.PP
Definition at line 39 of file Exceptions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
