.TH "fitdata" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitdata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NFWFit.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfitdata\fP (const size_t _n, const \fBreal\fP *_x, const \fBreal\fP *_y, const \fBreal\fP *_sigma)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const size_t \fBn\fP"
.br
.ti -1c
.RI "const \fBreal\fP * \fBx\fP"
.br
.ti -1c
.RI "const \fBreal\fP * \fBy\fP"
.br
.ti -1c
.RI "const \fBreal\fP * \fBsigma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file NFWFit.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fitdata::fitdata (const size_t _n, const \fBreal\fP * _x, const \fBreal\fP * _y, const \fBreal\fP * _sigma)\fC [inline]\fP"
.PP
Definition at line 47 of file NFWFit.h.
.SH "Field Documentation"
.PP 
.SS "const size_t \fBfitdata::n\fP"
.PP
Definition at line 42 of file NFWFit.h.
.PP
Referenced by NFW_df(), NFW_f(), and NFW_fix_fit().
.SS "const \fBreal\fP* \fBfitdata::sigma\fP"
.PP
Definition at line 45 of file NFWFit.h.
.PP
Referenced by NFW_df(), and NFW_f().
.SS "const \fBreal\fP* \fBfitdata::x\fP"
.PP
Definition at line 43 of file NFWFit.h.
.PP
Referenced by NFW_df(), NFW_f(), and NFW_fit().
.SS "const \fBreal\fP* \fBfitdata::y\fP"
.PP
Definition at line 44 of file NFWFit.h.
.PP
Referenced by NFW_f().

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
