.TH "fitdata_fix" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitdata_fix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NFWFit.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfitdata_fix\fP (const size_t _n, const \fBreal\fP *_x, const \fBreal\fP *_y, const \fBreal\fP *_sigma, const \fBreal\fP _rvir, const \fBreal\fP _mvir)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const size_t \fBn\fP"
.br
.ti -1c
.RI "const \fBreal\fP * \fBx\fP"
.br
.ti -1c
.RI "const \fBreal\fP * \fBy\fP"
.br
.ti -1c
.RI "const \fBreal\fP * \fBsigma\fP"
.br
.ti -1c
.RI "const \fBreal\fP \fBrvir\fP"
.br
.ti -1c
.RI "const \fBreal\fP \fBmvir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file NFWFit.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fitdata_fix::fitdata_fix (const size_t _n, const \fBreal\fP * _x, const \fBreal\fP * _y, const \fBreal\fP * _sigma, const \fBreal\fP _rvir, const \fBreal\fP _mvir)\fC [inline]\fP"
.PP
Definition at line 60 of file NFWFit.h.
.SH "Field Documentation"
.PP 
.SS "const \fBreal\fP \fBfitdata_fix::mvir\fP"
.PP
Definition at line 58 of file NFWFit.h.
.PP
Referenced by NFW_fix_df(), and NFW_fix_f().
.SS "const size_t \fBfitdata_fix::n\fP"
.PP
Definition at line 53 of file NFWFit.h.
.PP
Referenced by NFW_fit(), NFW_fix_df(), and NFW_fix_f().
.SS "const \fBreal\fP \fBfitdata_fix::rvir\fP"
.PP
Definition at line 57 of file NFWFit.h.
.PP
Referenced by NFW_fix_df(), and NFW_fix_f().
.SS "const \fBreal\fP* \fBfitdata_fix::sigma\fP"
.PP
Definition at line 56 of file NFWFit.h.
.PP
Referenced by NFW_fix_df(), and NFW_fix_f().
.SS "const \fBreal\fP* \fBfitdata_fix::x\fP"
.PP
Definition at line 54 of file NFWFit.h.
.PP
Referenced by NFW_fix_df(), NFW_fix_f(), and NFW_fix_fit().
.SS "const \fBreal\fP* \fBfitdata_fix::y\fP"
.PP
Definition at line 55 of file NFWFit.h.
.PP
Referenced by NFW_fix_f().

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
