.TH "GreensFunction" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GreensFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GreensFunction.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGreensFunction\fP (float dx)"
.br
.ti -1c
.RI "float \fBapply\fP (int k)"
.br
.ti -1c
.RI "template<> float \fBapply\fP (int k)"
.br
.ti -1c
.RI "template<> float \fBapply\fP (int k)"
.br
.ti -1c
.RI "template<> float \fBapply\fP (int k)"
.br
.ti -1c
.RI "template<> float \fBapply\fP (int k)"
.br
.ti -1c
.RI "template<> float \fBapply\fP (int k)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int nOrder> class GreensFunction< nOrder >"

.PP
Definition at line 32 of file GreensFunction.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<int nOrder> \fBGreensFunction\fP< nOrder >::\fBGreensFunction\fP (float dx)\fC [inline]\fP"
.PP
Definition at line 35 of file GreensFunction.h.
.SH "Member Function Documentation"
.PP 
.SS "template<> float \fBGreensFunction\fP< 11 >::apply (int k)\fC [inline]\fP"
.PP
Definition at line 70 of file GreensFunction.h.
.SS "template<> float \fBGreensFunction\fP< 9 >::apply (int k)\fC [inline]\fP"
.PP
Definition at line 61 of file GreensFunction.h.
.SS "template<> float \fBGreensFunction\fP< 7 >::apply (int k)\fC [inline]\fP"
.PP
Definition at line 53 of file GreensFunction.h.
.SS "template<> float \fBGreensFunction\fP< 5 >::apply (int k)\fC [inline]\fP"
.PP
Definition at line 46 of file GreensFunction.h.
.SS "template<> float \fBGreensFunction\fP< 3 >::apply (int k)\fC [inline]\fP"
.PP
Definition at line 40 of file GreensFunction.h.
.SS "template<int nOrder> float \fBGreensFunction\fP< nOrder >::apply (int k)\fC [inline]\fP"
.PP
Definition at line 31 of file GreensFunction.cpp.
.PP
Referenced by PoissonSolver< nstencil >::solve().

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
