.TH "GreensFunction.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GreensFunction.cpp \- 
.PP
implementations (non-templated) for Greensfunction  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'GreensFunction.h'\fP
.br

.SH "Detailed Description"
.PP 
implementations (non-templated) for Greensfunction 


.PP
Definition in file \fBGreensFunction.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
