.TH "GreensFunction.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GreensFunction.h \- 
.PP
implementation of Green's function G  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGreensFunction< nOrder >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
implementation of Green's function G 


.PP
Definition in file \fBGreensFunction.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
