.TH "HaloProperties.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HaloProperties.cpp \- 
.PP
Implementations of the \fBHaloProperties\fP class.  

.SH SYNOPSIS
.br
.PP
\fC#include 'HaloProperties.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'DataStruct.h'\fP
.br
\fC#include 'OctTree.h'\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'ANN/ANN.h'\fP
.br
\fC#include <gsl/gsl_vector.h>\fP
.br
\fC#include <gsl/gsl_blas.h>\fP
.br
\fC#include <gsl/gsl_multifit_nlin.h>\fP
.br
\fC#include <gsl/gsl_errno.h>\fP
.br
\fC#include 'Global.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementations of the \fBHaloProperties\fP class. 


.PP
Definition in file \fBHaloProperties.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
