.TH "Halo.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Halo.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Global.h'\fP
.br
\fC#include 'Distance.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br
\fC#include 'Matrix33.h'\fP
.br
\fC#include 'Halo.h'\fP
.br
\fC#include 'Simulation.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
