.TH "Halo.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Halo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Global.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br
\fC#include 'Matrix33.h'\fP
.br
\fC#include 'Eigensystem3.h'\fP
.br
\fC#include 'Cosmology.h'\fP
.br
\fC#include 'Simulation.h'\fP
.br
\fC#include 'Distance.h'\fP
.br
\fC#include 'OctTree.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHalo\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBOCTTREE\fP"
.br
.ti -1c
.RI "#define \fBFORCE_DIRECT_TREE_SPLIT\fP   4000"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FORCE_DIRECT_TREE_SPLIT   4000"
.PP
Definition at line 24 of file Halo.h.
.PP
Referenced by HaloProperties::CenterOnMB(), HaloProperties::ComputeMB(), and HaloProperties::ComputeMBExc().
.SS "#define OCTTREE"
.PP
Definition at line 23 of file Halo.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
