.TH "HaloProperties::Cosm" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HaloProperties::Cosm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HaloProperties.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBreal\fP \fBOmegaM0\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBOmegaL0\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBH0\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBG\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBasnap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file HaloProperties.h.
.SH "Field Documentation"
.PP 
.SS "\fBreal\fP \fBHaloProperties::Cosm::asnap\fP"
.PP
Definition at line 59 of file HaloProperties.h.
.PP
Referenced by HaloProperties::ComputeAngularMomentum(), HaloProperties::ComputeDensityProfile(), HaloProperties::ComputeKineticEnergy(), HaloProperties::ComputeKineticEnergyNoHubble(), HaloProperties::ComputeKineticEnergyNoHubbleExc(), HaloProperties::ComputeLambdaPrime(), HaloProperties::ComputePoormanConcentration(), HaloProperties::ComputePotentialDirect(), HaloProperties::ComputePotentialDirectExc(), HaloProperties::ComputePotentialTree(), HaloProperties::ComputePotentialTreeExc(), HaloProperties::ComputeVirialProperties(), HaloProperties::ComputeVirialProperties200(), and HaloProperties::HaloProperties().
.SS "\fBreal\fP \fBHaloProperties::Cosm::G\fP"
.PP
Definition at line 59 of file HaloProperties.h.
.PP
Referenced by HaloProperties::ComputeLambdaPrime(), HaloProperties::ComputePotentialDirect(), HaloProperties::ComputePotentialDirectExc(), HaloProperties::ComputePotentialTree(), HaloProperties::ComputePotentialTreeExc(), HaloProperties::ComputeVirialProperties(), HaloProperties::ComputeVirialProperties200(), HaloProperties::HaloProperties(), and HaloProperties::SetCosmology().
.SS "\fBreal\fP \fBHaloProperties::Cosm::H0\fP"
.PP
Definition at line 59 of file HaloProperties.h.
.PP
Referenced by HaloProperties::ComputeKineticEnergy(), HaloProperties::HaloProperties(), and HaloProperties::SetCosmology().
.SS "\fBreal\fP \fBHaloProperties::Cosm::OmegaL0\fP"
.PP
Definition at line 59 of file HaloProperties.h.
.PP
Referenced by HaloProperties::ComputeKineticEnergy(), HaloProperties::ComputeVirialProperties200(), HaloProperties::HaloProperties(), and HaloProperties::SetCosmology().
.SS "\fBreal\fP \fBHaloProperties::Cosm::OmegaM0\fP"
.PP
Definition at line 59 of file HaloProperties.h.
.PP
Referenced by HaloProperties::ComputeKineticEnergy(), HaloProperties::ComputeVirialProperties200(), HaloProperties::HaloProperties(), and HaloProperties::SetCosmology().

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
