.TH "HaloProperties::Distance" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HaloProperties::Distance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HaloProperties.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDistance\fP (\fBreal\fP r, unsigned i)"
.br
.ti -1c
.RI "\fBDistance\fP (const \fBDistance\fP &d)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBDistance\fP &d2) const "
.br
.ti -1c
.RI "\fBreal\fP \fBgetr\fP (void) const "
.br
.ti -1c
.RI "unsigned \fBgeti\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file HaloProperties.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HaloProperties::Distance::Distance (\fBreal\fP r, unsigned i)\fC [inline]\fP"
.PP
Definition at line 70 of file HaloProperties.h.
.SS "HaloProperties::Distance::Distance (const \fBDistance\fP & d)\fC [inline]\fP"
.PP
Definition at line 71 of file HaloProperties.h.
.SH "Member Function Documentation"
.PP 
.SS "unsigned HaloProperties::Distance::geti (void) const\fC [inline]\fP"
.PP
Definition at line 78 of file HaloProperties.h.
.SS "\fBreal\fP HaloProperties::Distance::getr (void) const\fC [inline]\fP"
.PP
Definition at line 75 of file HaloProperties.h.
.SS "bool HaloProperties::Distance::operator< (const \fBDistance\fP & d2) const\fC [inline]\fP"
.PP
Definition at line 72 of file HaloProperties.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
