.TH "HDFException" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDFException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HDFIO.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDFException\fP (const std::string &errtxt)"
.br
.ti -1c
.RI "\fBHDFException\fP (const std::string &errtxt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file HDFIO.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDFException::HDFException (const std::string & errtxt)\fC [inline]\fP"
.PP
Definition at line 59 of file HDFIO.h.
.SS "HDFException::HDFException (const std::string & errtxt)\fC [inline]\fP"
.PP
Definition at line 57 of file HDFIO_new.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
