.TH "HResults.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HResults.cpp \- 
.PP
all routines for \fBHResults.h\fP contains all different routines for storing and writing results from \fBHalo\fP  

.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include 'Global.h'\fP
.br
\fC#include 'HResults.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br
\fC#include 'Eigensystem3.h'\fP
.br

.SH "Detailed Description"
.PP 
all routines for \fBHResults.h\fP contains all different routines for storing and writing results from \fBHalo\fP 


.PP
Definition in file \fBHResults.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
