.TH "Matrix33.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix33.h \- 
.PP
All publicly known functions of \fBMatrix33.cpp\fP presents a 3x3 Matrix.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <gsl/gsl_math.h>\fP
.br
\fC#include <gsl/gsl_eigen.h>\fP
.br
\fC#include 'Global.h'\fP
.br
\fC#include 'Vector3.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMatrix33\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
All publicly known functions of \fBMatrix33.cpp\fP presents a 3x3 Matrix. 


.PP
Definition in file \fBMatrix33.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
