.TH "MaxProgenitorsExceed" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxProgenitorsExceed \- 
.PP
Exception: Maximum number of halo progenitors exceeded This exception is called if a progenitor halo is added to a given halo but that halo already possesses the maximum allowed number of progenitor haloes (standard 25). This happens for memory reasons and means you have to increase the number of allowed progenitors.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaxProgenitorsExceed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception: Maximum number of halo progenitors exceeded This exception is called if a progenitor halo is added to a given halo but that halo already possesses the maximum allowed number of progenitor haloes (standard 25). This happens for memory reasons and means you have to increase the number of allowed progenitors. 
.PP
Definition at line 50 of file Exceptions.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaxProgenitorsExceed::MaxProgenitorsExceed ()\fC [inline]\fP"
.PP
Definition at line 52 of file Exceptions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
