.TH "Output.cpp" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Output.cpp \- 
.PP
all output routines provides routines for accessing and writing AHF output as well as calculated \fBHalo\fP outputs.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'Output.h'\fP
.br

.SH "Detailed Description"
.PP 
all output routines provides routines for accessing and writing AHF output as well as calculated \fBHalo\fP outputs. 


.PP
Definition in file \fBOutput.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
