.TH "SubhaloMatch.h" 3 "10 May 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubhaloMatch.h \- 
.PP
All publicly known functions of \fBSubhaloMatch.cpp\fP.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSubhaloMatch\fP (unsigned isnap)"
.br
.in -1c
.SH "Detailed Description"
.PP 
All publicly known functions of \fBSubhaloMatch.cpp\fP. 


.PP
Definition in file \fBSubhaloMatch.h\fP.
.SH "Function Documentation"
.PP 
.SS "void SubhaloMatch (unsigned isnap)"
.PP
Definition at line 61 of file SubhaloMatch.cpp.
.PP
References DEBUG, donedebug(), Folder(), GetLineNumber(), GetMtreeFile(), Snaps(), writedebug(), and WriteMtree2File().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
