.TH "try.cpp" 3 "22 Mar 2010" "Version 0.1" "amateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
try.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <map>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfind4\fP (const std::map< unsigned, int > &dm)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void find4 (const std::map< unsigned, int > & dm)"
.PP
Definition at line 15 of file try.cpp.
.PP
Referenced by main().
.SS "int main ()"
.PP
Definition at line 20 of file try.cpp.
.PP
References find4().
.SH "Author"
.PP 
Generated automatically by Doxygen for amateur from the source code.
