!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitfd(f2pysetupfunc)
      use fd, only : dp
      use fd, only : lprsmf
      external f2pysetupfunc
      call f2pysetupfunc(dp,lprsmf)
      end subroutine f2pyinitfd

      
      subroutine f2pyinititimes(f2pysetupfunc)
      use itimes, only : mpi_sum
      use itimes, only : mpi_statuses_ignore
      use itimes, only : mpi_minloc
      use itimes, only : error
      use itimes, only : mpi_err_root
      use itimes, only : mpi_real
      use itimes, only : mpi_err_info_nokey
      use itimes, only : mpi_seek_set
      use itimes, only : mpi_lb
      use itimes, only : mpi_any_source
      use itimes, only : mpi_file_null
      use itimes, only : mpi_bor
      use itimes, only : mpi_signed_char
      use itimes, only : mpi_err_lastcode
      use itimes, only : mpi_wchar
      use itimes, only : mpi_err_dims
      use itimes, only : mpi_err_access
      use itimes, only : mpi_err_arg
      use itimes, only : mpi_long_double
      use itimes, only : mpi_order_c
      use itimes, only : mpi_complex32
      use itimes, only : mpi_err_info_value
      use itimes, only : mpi_uint16_t
      use itimes, only : mpi_char
      use itimes, only : mpi_distribute_block
      use itimes, only : mpi_err_not_same
      use itimes, only : wtime
      use itimes, only : mpi_in_place
      use itimes, only : mpi_group_null
      use itimes, only : mpi_integer16
      use itimes, only : mpi_ub
      use itimes, only : mpi_combiner_hvector_integer
      use itimes, only : mpi_err_no_space
      use itimes, only : mpi_err_op
      use itimes, only : mpi_mode_rdwr
      use itimes, only : errcode
      use itimes, only : mpi_err_group
      use itimes, only : mpi_seek_cur
      use itimes, only : mpi_err_comm
      use itimes, only : mpi_bxor
      use itimes, only : mpi_proc_null
      use itimes, only : mpi_combiner_resized
      use itimes, only : mpi_err_base
      use itimes, only : mpi_real8
      use itimes, only : mpi_err_rank
      use itimes, only : mpi_err_other
      use itimes, only : mpi_mode_noprecede
      use itimes, only : mpi_mode_unique_open
      use itimes, only : mpi_err_disp
      use itimes, only : mpi_errors_are_fatal
      use itimes, only : p_here
      use itimes, only : mpi_mode_noput
      use itimes, only : mpi_err_unknown
      use itimes, only : mpi_distribute_dflt_darg
      use itimes, only : mpi_float
      use itimes, only : mpi_status_ignore
      use itimes, only : mpi_similar
      use itimes, only : mpi_comm_null
      use itimes, only : mpi_int32_t
      use itimes, only : mpi_thread_single
      use itimes, only : mpix_message_no_proc
      use itimes, only : mpi_distribute_cyclic
      use itimes, only : mpi_prod
      use itimes, only : mpi_status_size
      use itimes, only : mpi_unsigned_long
      use itimes, only : mpi_host
      use itimes, only : mpi_typeclass_complex
      use itimes, only : mpi_combiner_indexed_block
      use itimes, only : mpi_typeclass_real
      use itimes, only : mpi_packed
      use itimes, only : mpi_dist_graph
      use itimes, only : mpi_error
      use itimes, only : mpi_combiner_dup
      use itimes, only : mpi_lxor
      use itimes, only : mpi_win_disp_unit
      use itimes, only : mpi_uint64_t
      use itimes, only : mpi_bsend_overhead
      use itimes, only : mpi_err_unsupported_datarep
      use itimes, only : mpi_int
      use itimes, only : mpi_root
      use itimes, only : mpi_integer4
      use itimes, only : mpi_order_fortran
      use itimes, only : mpi_err_info_key
      use itimes, only : mpi_any_tag
      use itimes, only : mpi_integer1
      use itimes, only : mpi_combiner_f90_real
      use itimes, only : mpi_address_kind
      use itimes, only : mpi_err_bad_file
      use itimes, only : mpi_err_topology
      use itimes, only : mpi_err_spawn
      use itimes, only : mpi_max_error_string
      use itimes, only : mpi_combiner_named
      use itimes, only : mpi_c_complex
      use itimes, only : mpi_errors_return
      use itimes, only : mpi_unsigned_short
      use itimes, only : mpi_combiner_f90_complex
      use itimes, only : mpi_long_double_int
      use itimes, only : mpi_err_service
      use itimes, only : mpi_2real
      use itimes, only : mpi_lor
      use itimes, only : mpi_typeclass_integer
      use itimes, only : mpi_mode_append
      use itimes, only : mpi_double
      use itimes, only : mpi_errcodes_ignore
      use itimes, only : mpi_2int
      use itimes, only : mpi_op_null
      use itimes, only : mpi_appnum
      use itimes, only : mpi_err_tag
      use itimes, only : mpi_win_null
      use itimes, only : mpi_2double_complex
      use itimes, only : mpi_double_precision
      use itimes, only : mpi_wtick
      use itimes, only : mpi_status
      use itimes, only : mpi_mode_nocheck
      use itimes, only : mpi_replace
      use itimes, only : id
      use itimes, only : mpi_err_port
      use itimes, only : pads_a
      use itimes, only : mpi_2complex
      use itimes, only : mpi_combiner_indexed
      use itimes, only : mpi_subversion
      use itimes, only : mpi_combiner_struct
      use itimes, only : mpi_mode_create
      use itimes, only : mpi_tag
      use itimes, only : mpi_datatype_null
      use itimes, only : mpi_err_pending
      use itimes, only : mpi_unsigned_char
      use itimes, only : mpi_c_long_double_complex
      use itimes, only : mpi_err_no_mem
      use itimes, only : mpi_offset_kind
      use itimes, only : mpi_int64_t
      use itimes, only : pmpi_wtick
      use itimes, only : mpi_io
      use itimes, only : mpi_success
      use itimes, only : mpi_uint32_t
      use itimes, only : mpi_mode_rdonly
      use itimes, only : mpi_thread_serialized
      use itimes, only : mpi_long_int
      use itimes, only : mpi_group_empty
      use itimes, only : mpi_thread_funneled
      use itimes, only : mpi_2double_precision
      use itimes, only : mpix_comm_type_shared
      use itimes, only : mpi_universe_size
      use itimes, only : mpi_version
      use itimes, only : mpi_logical
      use itimes, only : mpi_err_file_in_use
      use itimes, only : mpi_err_dup_datarep
      use itimes, only : mpi_bottom
      use itimes, only : mpi_uint8_t
      use itimes, only : mpi_err_count
      use itimes, only : mpi_win_base
      use itimes, only : mpix_message_null
      use itimes, only : mpi_err_type
      use itimes, only : mpi_lock_shared
      use itimes, only : mpi_max_info_key
      use itimes, only : mpi_complex
      use itimes, only : mpi_max
      use itimes, only : mpi_band
      use itimes, only : mpi_int8_t
      use itimes, only : mpi_cart
      use itimes, only : mpi_err_amode
      use itimes, only : mpi_mode_sequential
      use itimes, only : mpi_integer8
      use itimes, only : mpi_err_file_exists
      use itimes, only : mpi_combiner_hindexed_integer
      use itimes, only : mpi_combiner_subarray
      use itimes, only : mpi_short_int
      use itimes, only : mpi_err_name
      use itimes, only : mpi_complex8
      use itimes, only : mpi_combiner_hvector
      use itimes, only : mpi_long_long
      use itimes, only : pads_b
      use itimes, only : mpi_err_info
      use itimes, only : mpi_float_int
      use itimes, only : mpi_mode_nostore
      use itimes, only : mpi_err_rma_sync
      use itimes, only : mpi_byte
      use itimes, only : mpi_max_processor_name
      use itimes, only : mpi_thread_multiple
      use itimes, only : pmpi_wtime
      use itimes, only : mpi_comm_world
      use itimes, only : mpi_mode_nosucceed
      use itimes, only : mpi_info_null
      use itimes, only : mpi_max_info_val
      use itimes, only : mpi_long
      use itimes, only : mpi_tag_ub
      use itimes, only : mpi_congruent
      use itimes, only : mpi_errhandler_null
      use itimes, only : mpi_err_assert
      use itimes, only : mpi_combiner_darray
      use itimes, only : mpi_err_truncate
      use itimes, only : mpi_err_win
      use itimes, only : mpi_2integer
      use itimes, only : mpi_complex16
      use itimes, only : mpi_keyval_invalid
      use itimes, only : mpi_int16_t
      use itimes, only : mpi_combiner_hindexed
      use itimes, only : mpi_unsigned
      use itimes, only : mpi_err_read_only
      use itimes, only : mpi_err_quota
      use itimes, only : mpi_combiner_struct_integer
      use itimes, only : mpi_err_unsupported_operation
      use itimes, only : mpi_c_double_complex
      use itimes, only : mpi_double_int
      use itimes, only : mpi_max_object_name
      use itimes, only : mpi_short
      use itimes, only : mpi_integer2
      use itimes, only : mpi_err_keyval
      use itimes, only : mpi_unequal
      use itimes, only : mpi_win_size
      use itimes, only : mpi_displacement_current
      use itimes, only : mpi_err_size
      use itimes, only : mpi_mode_delete_on_close
      use itimes, only : mpi_lock_exclusive
      use itimes, only : mpi_mode_wronly
      use itimes, only : mpi_err_request
      use itimes, only : mpi_min
      use itimes, only : mpi_land
      use itimes, only : mpi_source
      use itimes, only : mpi_real16
      use itimes, only : mpi_lastusedcode
      use itimes, only : mpi_err_io
      use itimes, only : mpi_err_no_such_file
      use itimes, only : mpi_wtime
      use itimes, only : mpi_err_intern
      use itimes, only : mpi_character
      use itimes, only : mpi_combiner_f90_integer
      use itimes, only : mpi_maxloc
      use itimes, only : mpi_integer_kind
      use itimes, only : mpi_aint
      use itimes, only : mpi_double_complex
      use itimes, only : mpi_real4
      use itimes, only : mpi_err_conversion
      use itimes, only : mpi_err_rma_conflict
      use itimes, only : mpi_comm_self
      use itimes, only : mpi_mode_excl
      use itimes, only : mpi_combiner_vector
      use itimes, only : mpi_err_in_status
      use itimes, only : mpi_combiner_contiguous
      use itimes, only : mpi_c_bool
      use itimes, only : mpi_argvs_null
      use itimes, only : mpi_offset
      use itimes, only : mpi_ident
      use itimes, only : mpi_request_null
      use itimes, only : mpi_seek_end
      use itimes, only : mpi_integer
      use itimes, only : mpi_err_locktype
      use itimes, only : mpi_long_long_int
      use itimes, only : mpi_graph
      use itimes, only : mpi_err_file
      use itimes, only : mpix_combiner_hindexed_block
      use itimes, only : mpi_max_datarep_string
      use itimes, only : mpi_undefined
      use itimes, only : mpi_max_port_name
      use itimes, only : mpi_distribute_none
      use itimes, only : mpi_err_buffer
      use itimes, only : mpi_argv_null
      use itimes, only : mpi_unsigned_long_long
      use itimes, only : mpi_c_float_complex
      use itimes, only : mpi_unweighted
      use itimes, only : mpi_wtime_is_global
      use itimes, only : test
      use itimes, only : mytime
      external f2pysetupfunc
      call f2pysetupfunc(mpi_sum,mpi_statuses_ignore,mpi_minloc,error,mp&
     &i_err_root,mpi_real,mpi_err_info_nokey,mpi_seek_set,mpi_lb,mpi_any&
     &_source,mpi_file_null,mpi_bor,mpi_signed_char,mpi_err_lastcode,mpi&
     &_wchar,mpi_err_dims,mpi_err_access,mpi_err_arg,mpi_long_double,mpi&
     &_order_c,mpi_complex32,mpi_err_info_value,mpi_uint16_t,mpi_char,mp&
     &i_distribute_block,mpi_err_not_same,wtime,mpi_in_place,mpi_group_n&
     &ull,mpi_integer16,mpi_ub,mpi_combiner_hvector_integer,mpi_err_no_s&
     &pace,mpi_err_op,mpi_mode_rdwr,errcode,mpi_err_group,mpi_seek_cur,m&
     &pi_err_comm,mpi_bxor,mpi_proc_null,mpi_combiner_resized,mpi_err_ba&
     &se,mpi_real8,mpi_err_rank,mpi_err_other,mpi_mode_noprecede,mpi_mod&
     &e_unique_open,mpi_err_disp,mpi_errors_are_fatal,p_here,mpi_mode_no&
     &put,mpi_err_unknown,mpi_distribute_dflt_darg,mpi_float,mpi_status_&
     &ignore,mpi_similar,mpi_comm_null,mpi_int32_t,mpi_thread_single,mpi&
     &x_message_no_proc,mpi_distribute_cyclic,mpi_prod,mpi_status_size,m&
     &pi_unsigned_long,mpi_host,mpi_typeclass_complex,mpi_combiner_index&
     &ed_block,mpi_typeclass_real,mpi_packed,mpi_dist_graph,mpi_error,mp&
     &i_combiner_dup,mpi_lxor,mpi_win_disp_unit,mpi_uint64_t,mpi_bsend_o&
     &verhead,mpi_err_unsupported_datarep,mpi_int,mpi_root,mpi_integer4,&
     &mpi_order_fortran,mpi_err_info_key,mpi_any_tag,mpi_integer1,mpi_co&
     &mbiner_f90_real,mpi_address_kind,mpi_err_bad_file,mpi_err_topology&
     &,mpi_err_spawn,mpi_max_error_string,mpi_combiner_named,mpi_c_compl&
     &ex,mpi_errors_return,mpi_unsigned_short,mpi_combiner_f90_complex,m&
     &pi_long_double_int,mpi_err_service,mpi_2real,mpi_lor,mpi_typeclass&
     &_integer,mpi_mode_append,mpi_double,mpi_errcodes_ignore,mpi_2int,m&
     &pi_op_null,mpi_appnum,mpi_err_tag,mpi_win_null,mpi_2double_complex&
     &,mpi_double_precision,mpi_wtick,mpi_status,mpi_mode_nocheck,mpi_re&
     &place,id,mpi_err_port,pads_a,mpi_2complex,mpi_combiner_indexed,mpi&
     &_subversion,mpi_combiner_struct,mpi_mode_create,mpi_tag,mpi_dataty&
     &pe_null,mpi_err_pending,mpi_unsigned_char,mpi_c_long_double_comple&
     &x,mpi_err_no_mem,mpi_offset_kind,mpi_int64_t,pmpi_wtick,mpi_io,mpi&
     &_success,mpi_uint32_t,mpi_mode_rdonly,mpi_thread_serialized,mpi_lo&
     &ng_int,mpi_group_empty,mpi_thread_funneled,mpi_2double_precision,m&
     &pix_comm_type_shared,mpi_universe_size,mpi_version,mpi_logical,mpi&
     &_err_file_in_use,mpi_err_dup_datarep,mpi_bottom,mpi_uint8_t,mpi_er&
     &r_count,mpi_win_base,mpix_message_null,mpi_err_type,mpi_lock_share&
     &d,mpi_max_info_key,mpi_complex,mpi_max,mpi_band,mpi_int8_t,mpi_car&
     &t,mpi_err_amode,mpi_mode_sequential,mpi_integer8,mpi_err_file_exis&
     &ts,mpi_combiner_hindexed_integer,mpi_combiner_subarray,mpi_short_i&
     &nt,mpi_err_name,mpi_complex8,mpi_combiner_hvector,mpi_long_long,pa&
     &ds_b,mpi_err_info,mpi_float_int,mpi_mode_nostore,mpi_err_rma_sync,&
     &mpi_byte,mpi_max_processor_name,mpi_thread_multiple,pmpi_wtime,mpi&
     &_comm_world,mpi_mode_nosucceed,mpi_info_null,mpi_max_info_val,mpi_&
     &long,mpi_tag_ub,mpi_congruent,mpi_errhandler_null,mpi_err_assert,m&
     &pi_combiner_darray,mpi_err_truncate,mpi_err_win,mpi_2integer,mpi_c&
     &omplex16,mpi_keyval_invalid,mpi_int16_t,mpi_combiner_hindexed,mpi_&
     &unsigned,mpi_err_read_only,mpi_err_quota,mpi_combiner_struct_integ&
     &er,mpi_err_unsupported_operation,mpi_c_double_complex,mpi_double_i&
     &nt,mpi_max_object_name,mpi_short,mpi_integer2,mpi_err_keyval,mpi_u&
     &nequal,mpi_win_size,mpi_displacement_current,mpi_err_size,mpi_mode&
     &_delete_on_close,mpi_lock_exclusive,mpi_mode_wronly,mpi_err_reques&
     &t,mpi_min,mpi_land,mpi_source,mpi_real16,mpi_lastusedcode,mpi_err_&
     &io,mpi_err_no_such_file,mpi_wtime,mpi_err_intern,mpi_character,mpi&
     &_combiner_f90_integer,mpi_maxloc,mpi_integer_kind,mpi_aint,mpi_dou&
     &ble_complex,mpi_real4,mpi_err_conversion,mpi_err_rma_conflict,mpi_&
     &comm_self,mpi_mode_excl,mpi_combiner_vector,mpi_err_in_status,mpi_&
     &combiner_contiguous,mpi_c_bool,mpi_argvs_null,mpi_offset,mpi_ident&
     &,mpi_request_null,mpi_seek_end,mpi_integer,mpi_err_locktype,mpi_lo&
     &ng_long_int,mpi_graph,mpi_err_file,mpix_combiner_hindexed_block,mp&
     &i_max_datarep_string,mpi_undefined,mpi_max_port_name,mpi_distribut&
     &e_none,mpi_err_buffer,mpi_argv_null,mpi_unsigned_long_long,mpi_c_f&
     &loat_complex,mpi_unweighted,mpi_wtime_is_global,test,mytime)
      end subroutine f2pyinititimes


