C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitmpifcmb4(setupfunc)
      external setupfunc
      integer mpi_in_place
      common /mpifcmb4/ mpi_in_place
      call setupfunc(mpi_in_place)
      end

      subroutine f2pyinitmpifcmb2(setupfunc)
      external setupfunc
      integer mpi_statuses_ignore(5,1)
      common /mpifcmb2/ mpi_statuses_ignore
      call setupfunc(mpi_statuses_ignore)
      end

      subroutine f2pyinitmpifcmb5(setupfunc)
      external setupfunc
      integer mpi_unweighted
      common /mpifcmb5/ mpi_unweighted
      call setupfunc(mpi_unweighted)
      end

      subroutine f2pyinitmpifcmb3(setupfunc)
      external setupfunc
      integer mpi_bottom
      common /mpifcmb3/ mpi_bottom
      call setupfunc(mpi_bottom)
      end

      subroutine f2pyinitmpifcmb6(setupfunc)
      external setupfunc
      integer mpi_errcodes_ignore(1)
      common /mpifcmb6/ mpi_errcodes_ignore
      call setupfunc(mpi_errcodes_ignore)
      end

      subroutine f2pyinitmpifcmb1(setupfunc)
      external setupfunc
      integer mpi_status_ignore(5)
      common /mpifcmb1/ mpi_status_ignore
      call setupfunc(mpi_status_ignore)
      end

      subroutine f2pyinitmpifcmb8(setupfunc)
      external setupfunc
      character mpi_argv_null(1,1)
      character pads_b(3,1)
      common /mpifcmb8/ mpi_argv_null,pads_b
      call setupfunc(mpi_argv_null,pads_b)
      end

      subroutine f2pyinitmpifcmb7(setupfunc)
      external setupfunc
      character mpi_argvs_null(1,1,1)
      character pads_a(3,1)
      common /mpifcmb7/ mpi_argvs_null,pads_a
      call setupfunc(mpi_argvs_null,pads_a)
      end


