AHFrun.cpp File Reference
Call AHFstep from AMIGA.
#include <fstream>
#include <iostream>
#include <string>
#include `Global.h`
Functions
void CreateAHFParameterFile (unsigned isnap)
Creates the parameter file for AHFstep Creates the parameter file for AHFstep in output directory.
void RunAHFstep (unsigned isnap)
calls AHFstep runs AHFstep parameterfile
void MoveAHFout (unsigned isnap)
move output files of AHFstep Moves output files from current directory to output/[snap-string]
void RenameAHFout (unsigned isnap)
Renames AHFstep output files Renames output files of AHFstep using regexpressions with bash.
void AHFrun (unsigned isnap)
Controls execution of AHFstep.
Detailed Description
Call AHFstep from AMIGA.
Definition in file AHFrun.cpp.
Function Documentation
void AHFrun (unsigned isnap)
Controls execution of AHFstep.
Creates the parameter file, invokes AHFstep, moves output files and renames them
Parameters
isnap snapshot ID
Returns
void
Definition at line 139 of file AHFrun.cpp.
References CreateAHFParameterFile(), MoveAHFout(), RenameAHFout(), and RunAHFstep().
Referenced by main().
void CreateAHFParameterFile (unsigned isnap)
Creates the parameter file for AHFstep Creates the parameter file for AHFstep in output directory.
Parameters
isnap snapshot ID
Returns
void
Definition at line 39 of file AHFrun.cpp.
References DEBUG, donedebug(), Folder(), Snaps(), and writedebug().
Referenced by AHFrun().
void MoveAHFout (unsigned isnap)
move output files of AHFstep Moves output files from current directory to output/[snap-string]
Parameters
isnap snapshot ID
Returns
void
Definition at line 86 of file AHFrun.cpp.
References DEBUG, donedebug(), Folder(), RunCommand(), Snaps(), and writedebug().
Referenced by AHFrun().
void RenameAHFout (unsigned isnap)
Renames AHFstep output files Renames output files of AHFstep using regexpressions with bash.
Parameters
isnap snapshot ID
Returns
void
Definition at line 104 of file AHFrun.cpp.
References DEBUG, donedebug(), Folder(), RunCommand(), Snaps(), and writedebug().
Referenced by AHFrun().
void RunAHFstep (unsigned isnap)
calls AHFstep runs AHFstep parameterfile
Parameters
isnap snapshot ID
Returns
void
Definition at line 71 of file AHFrun.cpp.
References DEBUG, donedebug(), Folder(), RunCommand(), Snaps(), and writelndebug().
Referenced by AHFrun().