amateur.cpp File Reference
Main program, calls all subroutines.
#include <iostream>
#include <string>
#include <sys/resource.h>
#include `Global.h`
#include `ExtractSnap.h`
#include <math.h>
#include <fstream>
#include <iomanip>
#include <list>
#include <vector>
#include <iterator>
#include <cassert>
#include <gsl/gsl_math.h>
#include <gsl/gsl_eigen.h>
#include `Vector3.h`
#include `Matrix33.h`
#include <cmath>
#include `Array3.h`
#include `fftw3.h`
#include `TidalField.h`
#include `ScalarField.h`
Functions
void HelpUser (void)
Help for use of commandline arguments. example program calls: amateur 10 -t looks at tarkin_13309_CSF_45x_snap_211 and computes the tidal field amateur 1 runs all parts on tarkin_5726_10x_snap_302.
int main (int argc, char *argv[])
main routine, calls different tools The main routine of amateur presents the user a tool to select from the different possibilities to run the program, and on which snapshot file a command should be performed. If no arguments are given, amateur prints a help message showing the command syntax with all possible snapshots
Detailed Description
Main program, calls all subroutines.
Definition in file amateur.cpp.
Function Documentation
void HelpUser (void)
Help for use of commandline arguments. example program calls: amateur 10 -t looks at tarkin_13309_CSF_45x_snap_211 and computes the tidal field amateur 1 runs all parts on tarkin_5726_10x_snap_302.
program runs on nice value 15 by default attention: option -a requires a lot of CPU power, use a fast comoputer via ssh! -z requires a lot of memory -s and -x show excessive file access. For fast execution, use local computer (no ssh).
Definition at line 48 of file amateur.cpp.
References Snaps(), and writeln().
Referenced by main().
int main (int argc, char * argv[])
main routine, calls different tools The main routine of amateur presents the user a tool to select from the different possibilities to run the program, and on which snapshot file a command should be performed. If no arguments are given, amateur prints a help message showing the command syntax with all possible snapshots
Parameters
argc,: int; number of arguments
argv,: char* []; character array of arguments
Definition at line 77 of file amateur.cpp.
References AHFrun(), AnalyzeSnap(), AOutput(), ExtractSnap(), ScalarField::getValue(), Array3::getValue(), HelpUser(), MergerTreeRun(), ScalarField::setValue(), Array3::setValue(), Snaps(), SubhaloMatch(), PoissonSolver< nstencil >::test(), ScalarField::test(), TidalField(), and writeln().