AnalyzeSnap.cpp File Reference
Analyzes a given snapshot with Halo, for all particle types.
#include <cassert>
#include <fstream>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <string>
#include <vector>
#include `Global.h`
#include `Vector3.h`
#include `Matrix33.h`
#include `Eigensystem3.h`
#include `ReadGadget.h`
#include `Cosmology.h`
#include `Simulation.h`
#include <stack>
#include <queue>
#include <cmath>
#include <stdexcept>
#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <typeinfo>
#include `hdf5.h`
#include `AResults.h`
#include `HResults.h`
Typedefs
typedef std::vector< double > VecDouble
typedef std::vector< std::vector< double > > VecVecDouble
Functions
template<typename T >
T byteorder (T v)
little/big endian conversion conversion between little/big endian
void GetOffsets (unsigned *ParticleIDOffsets, unsigned *npart)
Return offsets of particle types inside snapshot. Get the particle ID offsets of the different particle types.
void readDataBlocks (int isnap, int TotalNOParticles, int *&id, real *&pos, real *&vel, real *&mass)
Read snapshot data Fill in all information from snapshot data file (id, pos, vel, mass).
void openParticlesFile (unsigned isnap, std::ifstream &ParticlesFile)
Open the ahf_out_particles file take ifstream and open particles file with it.
void ReadSnapIdType (std::ifstream &ParticlesFile, unsigned HaloPopulation, unsigned *&pid, int *&ptype)
Read a halo full of snapshot particles from ahf_out_particles Read in a slab of HaloPopulation particles.
void GenerateHalo (std::ifstream &ParticlesFile, unsigned HaloPopulation, const std::map< int, unsigned > &DoubleIndexMapi, real *pos, real *vel, real *mass, real *hpos, real *hvel, real *hmass, int *htype)
preparing halo extract new lists from pos, vel, mass based on id (AHF_particles)
void GenerateDIM (unsigned TotalNOParticles, int *&id, std::map< int, unsigned > &DIM)
generate doubly indexed map DIM for particle ID to occurence position
void AnalyzeSnap (unsigned isnap)
Analysis of one single snapshot file Analyzes a single snapshot file.
Variables
const int HaloTypeTotal = 5
const int ParticleTypeTotal = 6
Detailed Description
Analyzes a given snapshot with Halo, for all particle types.
Definition in file AnalyzeSnap.cpp.
Typedef Documentation
typedef std::vector<double> VecDouble
Definition at line 55 of file AnalyzeSnap.cpp.
typedef std::vector<std::vector <double> > VecVecDouble
Definition at line 56 of file AnalyzeSnap.cpp.
Function Documentation
void AnalyzeSnap (unsigned isnap)
Analysis of one single snapshot file Analyzes a single snapshot file.
Parameters
isnap unsigned snapshot ID
Returns
void
properties depending on halo type all: 1 1 1 1 15 dec dm: 0 0 1 1 3 dec gas: 0 1 0 0 4 dec stars: 1 0 0 0 8 dec bary: 1 1 0 0 12 dec
Definition at line 240 of file AnalyzeSnap.cpp.
References Output::appendHR(), Halo::calcJ(), Halo::calcLambda(), Halo::calcMpart(), Halo::calcNpart(), Halo::calcShape(), Halo::calcSigma(), DEBUG, Output::fillHRglobal(), Output::fillHRtype(), Folder(), GenerateDIM(), GenerateHalo(), get_particle_number(), Eigensystem3::getEval(), Halo::getMtot(), Halo::getMvir(), Halo::getRtot(), Halo::getRvir(), Halo::getVCM(), Halo::getVMB(), Halo::getXCM(), Halo::getXMB(), openParticlesFile(), ParticleTypeTotal, readDataBlocks(), Simulation::setBoxlength(), Simulation::setIsnap(), Simulation::setMass(), Simulation::setNhalo(), Simulation::setTarkinOmega(), Simulation::setZsnap(), Snaps(), Output::writeHR(), Output::writeHRstripped(), writeln(), and writelndebug().
Referenced by main().
template<typename T > T byteorder (T v) [inline]
little/big endian conversion conversion between little/big endian
Parameters
v
Returns
templated T value, in other byteorder
Definition at line 67 of file AnalyzeSnap.cpp.
void GenerateDIM (unsigned TotalNOParticles, int *& id, std::map< int, unsigned > & DIM)
generate doubly indexed map DIM for particle ID to occurence position
Parameters
TotalNOParticles; unsigned
id,: int* &; identification int for all particles in simulation
DIM,: std::map<int,unsigned>&; output
Returns
void
Definition at line 225 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap().
void GenerateHalo (std::ifstream & ParticlesFile, unsigned HaloPopulation, const std::map< int, unsigned > & DoubleIndexMapi, real * pos, real * vel, real * mass, real * hpos, real * hvel, real * hmass, int * htype)
preparing halo extract new lists from pos, vel, mass based on id (AHF_particles)
Parameters
ParticlesFile,: std::ifstream& of ahf_out_particles
HaloPopulation,: unsigned; number of particles total
DoubleIndexMapi,: map with reverse lookup possibility
pos,vel,mass,: const real *&, original data
hpos,hvel,hmass,: real *&, data for halo
htype,: particle type for halo
Returns
void
Definition at line 190 of file AnalyzeSnap.cpp.
References ReadSnapIdType().
Referenced by AnalyzeSnap().
void GetOffsets (unsigned * ParticleIDOffsets, unsigned * npart)
Return offsets of particle types inside snapshot. Get the particle ID offsets of the different particle types.
Parameters
ParticleIDOffsets,: unsigned*; where the offsets are stored
npart,: unsigned*; counts of particles types
Returns
void
Definition at line 88 of file AnalyzeSnap.cpp.
References ParticleTypeTotal.
void openParticlesFile (unsigned isnap, std::ifstream & ParticlesFile)
Open the ahf_out_particles file take ifstream and open particles file with it.
Parameters
isnap,: unsigned of which snapshot, see SystemCharacteristics
ParticlesFile,: ifstream by ref
Returns
void
Definition at line 145 of file AnalyzeSnap.cpp.
References Folder(), and Snaps().
Referenced by AnalyzeSnap().
void readDataBlocks (int isnap, int TotalNOParticles, int *& id, real *& pos, real *& vel, real *& mass)
Read snapshot data Fill in all information from snapshot data file (id, pos, vel, mass).
Parameters
isnap,: int; snapshot number
TotalNOParticles,: int
id,: is int &
pos,: is double & (3d)
vel,: is double & (3d)
mass,: is double & (1d)
Returns
void
Definition at line 111 of file AnalyzeSnap.cpp.
References Folder(), read_gadget_1(), read_gadget_3(), and Snaps().
Referenced by AnalyzeSnap().
void ReadSnapIdType (std::ifstream & ParticlesFile, unsigned HaloPopulation, unsigned *& pid, int *& ptype)
Read a halo full of snapshot particles from ahf_out_particles Read in a slab of HaloPopulation particles.
Parameters
ParticlesFile,: ifstream of ahf_out_particles
HaloPopulation,: unsigned int of number of particles in this halo
pid,: holds the output, all identifiers
ptype,: holds the output, all types, in accordance with ParticleIndexID
Definition at line 163 of file AnalyzeSnap.cpp.
Referenced by GenerateHalo().
Variable Documentation
const int HaloTypeTotal = 5
Definition at line 58 of file AnalyzeSnap.cpp.
const int ParticleTypeTotal = 6
Definition at line 59 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and GetOffsets().