AnalyzeSnap.h File Reference
All publicly known functions of AnalyzeSnap.cpp.
Functions
int AnalyzeSnap (unsigned isnap)
Analysis of one single snapshot file Analyzes a single snapshot file.
Detailed Description
All publicly known functions of AnalyzeSnap.cpp.
Definition in file AnalyzeSnap.h.
Function Documentation
int AnalyzeSnap (unsigned isnap)
Analysis of one single snapshot file Analyzes a single snapshot file.
Parameters
isnap unsigned snapshot ID
Returns
void
properties depending on halo type all: 1 1 1 1 15 dec dm: 0 0 1 1 3 dec gas: 0 1 0 0 4 dec stars: 1 0 0 0 8 dec bary: 1 1 0 0 12 dec
Definition at line 240 of file AnalyzeSnap.cpp.
References Output::appendHR(), Halo::calcJ(), Halo::calcLambda(), Halo::calcMpart(), Halo::calcNpart(), Halo::calcShape(), Halo::calcSigma(), DEBUG, Output::fillHRglobal(), Output::fillHRtype(), Folder(), GenerateDIM(), GenerateHalo(), get_particle_number(), Eigensystem3::getEval(), Halo::getMtot(), Halo::getMvir(), Halo::getRtot(), Halo::getRvir(), Halo::getVCM(), Halo::getVMB(), Halo::getXCM(), Halo::getXMB(), openParticlesFile(), ParticleTypeTotal, readDataBlocks(), Simulation::setBoxlength(), Simulation::setIsnap(), Simulation::setMass(), Simulation::setNhalo(), Simulation::setTarkinOmega(), Simulation::setZsnap(), Snaps(), Output::writeHR(), Output::writeHRstripped(), writeln(), and writelndebug().
Referenced by main().