AOutput.h File Reference
wrapper for AHF output
Functions
void AOutput (int isnap)
Detailed Description
wrapper for AHF output
Definition in file AOutput.h.
Function Documentation
void AOutput (int isnap)
Definition at line 32 of file AOutput.cpp.
References Output::getAR(), Simulation::setIsnap(), and Output::writeAR().
Referenced by main().