AOutput.cpp File Reference
rewrite ahf_out_halos for MATLAB input
#include `AOutput.h`
#include `Output.h`
#include `Simulation.h`
#include `Global.h`
Functions
void AOutput (int isnap)
Detailed Description
rewrite ahf_out_halos for MATLAB input
Definition in file AOutput.cpp.
Function Documentation
void AOutput (int isnap)
Definition at line 32 of file AOutput.cpp.
References Output::getAR(), Simulation::setIsnap(), and Output::writeAR().
Referenced by main().