bu_AnalyzeSnap_Halo2.cpp File Reference
#include <cassert>
#include <fstream>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <string>
#include <vector>
#include `SystemCharacteristics.h`
#include `Vector3.h`
#include `Matrix33.h`
#include `ReadGadget.h`
#include `Simulation.h`
#include `Halo.h`
#include `HDFIO.h`
Typedefs
typedef std::vector< double > VecDouble
typedef std::vector< std::vector< double > > VecVecDouble
Functions
VecVecDouble Vhp_Mass (HaloTypeTotal)
VecVecDouble Vhp_LambdaPrime (HaloTypeTotal)
VecVecDouble Vhp_Sigma (HaloTypeTotal)
VecVecDouble Vhp_J (HaloTypeTotal)
VecVecDouble Vhp_EVa (HaloTypeTotal)
VecVecDouble Vhp_EVb (HaloTypeTotal)
VecVecDouble Vhp_EVc (HaloTypeTotal)
VecVecDouble Vhp_Eigenvalues (HaloTypeTotal)
std::vector< std::vector< unsigned > > Vhp_HaloParticlesTypesCount (HaloTypeTotal)
template<typename T>
T byteorder (T v)
void Storeahf (int isnap)
void WriteHDF5 (std::string filename, double Boxsize, double Redshift, double HaloTotCount)
write all calculated properties into a HDF5 file This function takes all publicly known variables and writes them to disk
void GetOffsets (unsigned *ParticleIDOffsets, unsigned *npart)
Return offsets of particle types inside snapshot.
void ReadDataBlocks (std::string SnapshotFilename, int TotalNOParticles, int *&id, real *&pos, real *&vel, real *&mass)
Read snapshot data.
void openParticlesFile (unsigned isnap, std::ifstream &SnapshotParticles)
Open the ahf_out_particles file take ifstream and open particles file with it.
void PushBackHPoutput (unsigned HaloTypeIterator, Vector3 J, std::vector< Vector3 > Eigenvectors, Vector3 Eigenvalues, double lambda, double Mtot, double Sigma)
Push back all HP outputs for the different halos Push back onto the Vhp_ vectors the respective values.
void ReadSnapParticlesBunch (std::ifstream &SnapshotParticles, unsigned HaloPopulation, unsigned *&ParticleIndexID, int *&ParticleIndexType)
Read a halo full of snapshot particles from ahf_out_particles Read in a slab of HaloPopulation particles.
void GenerateHalo2 (unsigned HaloPopulation, std::ifstream &SnapshotParticles, const std::map< int, unsigned > &DoubleIndexMapi, unsigned *&ParticleCounter, unsigned *&ParticleOffset, real *&pos, real *&vel, real *&mass, real *&pos2, real *&vel2, real *&mass2)
preparing halo2 change position of values in pos, vel, mass according to particle type, should go into Halo as SubhaloCreation
void AnalyzeSnap (unsigned isnap)
Analysis of one single snapshot file Analyzes a single snapshot file.
Variables
const int HaloTypeTotal = 4
const int ParticleTypeTotal = 6
const double Omega_M = 0.3
const double h = 0.7
double rhobox = 0.0
VecDouble Vhp_PosCM
VecDouble Vhp_PosMB
VecDouble Vhp_VelCM
VecDouble Vhp_Rvir
VecDouble Vhp_Mvir
std::vector< unsigned > Vhp_HaloParticlesCount
VecDouble Vahf_npart
VecDouble Vahf_nvpart
VecDouble Vahf_ovdens
VecDouble Vahf_sigV
VecDouble Vahf_J
VecDouble Vahf_EW
VecDouble Vahf_EVa
VecDouble Vahf_EVb
VecDouble Vahf_EVc
VecDouble Vahf_Ekin
VecDouble Vahf_Epot
VecDouble Vahf_xc
Typedef Documentation
typedef std::vector<double> VecDouble
Definition at line 51 of file bu_AnalyzeSnap_Halo2.cpp.
typedef std::vector<std::vector <double> > VecVecDouble
Definition at line 52 of file bu_AnalyzeSnap_Halo2.cpp.
Function Documentation
void AnalyzeSnap (unsigned isnap)
Analysis of one single snapshot file Analyzes a single snapshot file.
Parameters:
isnap unsigned snapshot ID
Returns: void
Definition at line 391 of file bu_AnalyzeSnap_Halo2.cpp.
References Halo::calcABC(), Halo::calcEV(), Halo::calcJ(), Halo::calcLambda(), Halo::calcSigma(), DEBUG, Folder(), GenerateHalo(), GenerateHalo2(), get_particle_number(), Halo::getMtot(), Halo::getMvir(), GetOffsets(), Halo::getRvir(), Halo::getVCM(), Halo::getXCM(), Halo::getXMB(), HaloTypeTotal, openParticlesFile(), ParticleTypeTotal, PushBackHPoutput(), ReadDataBlocks(), Simulation::setZsnap(), Snaps(), Storeahf(), Matrix33::toVecVector3(), Vhp_HaloParticlesCount, Vhp_Mvir, Vhp_PosCM, Vhp_PosMB, Vhp_Rvir, Vhp_VelCM, writedebug(), WriteHDF5(), writeln(), and writelndebug().
template<typename T> T byteorder (T v) [inline]
conversion between little/big endian
Parameters:
v
Returns:
Definition at line 85 of file bu_AnalyzeSnap_Halo2.cpp.
void GenerateHalo2 (unsigned HaloPopulation, std::ifstream & SnapshotParticles, const std::map< int, unsigned > & DoubleIndexMapi, unsigned *& ParticleCounter, unsigned *& ParticleOffset, real *& pos, real *& vel, real *& mass, real *& pos2, real *& vel2, real *& mass2)
preparing halo2 change position of values in pos, vel, mass according to particle type, should go into Halo as SubhaloCreation
Parameters:
HaloPopulation,: unsigned particles total
SnapshotParticles,: std::ifstream of ahf_out_particles
DoubleIndexMap,: map with reverse lookup possibility
particleCounter,: unsigned *&, holds of particles per type
ParticleOffset,: unsigned *&, holds relevant parts of accumulated particleCounter
pos,vel,mass,: const double *&, original data
pos2,vel2,mass2,: double *&, data for this halo, sorted by particle type
Definition at line 331 of file bu_AnalyzeSnap_Halo2.cpp.
References HaloTypeTotal, ParticleTypeTotal, ReadSnapParticlesBunch(), and Vhp_HaloParticlesTypesCount().
Referenced by AnalyzeSnap().
void GetOffsets (unsigned * ParticleIDOffsets, unsigned * npart)
Return offsets of particle types inside snapshot.
Definition at line 208 of file bu_AnalyzeSnap_Halo2.cpp.
References ParticleTypeTotal.
void openParticlesFile (unsigned isnap, std::ifstream & SnapshotParticles)
Open the ahf_out_particles file take ifstream and open particles file with it.
Parameters:
isnap,: unsigned of which snapshot, see SystemCharacteristics
SnapshotParticles,: ifstream by ref
Returns: void
Definition at line 263 of file bu_AnalyzeSnap_Halo2.cpp.
References Folder(), and Snaps().
void PushBackHPoutput (unsigned HaloTypeIterator, Vector3 J, std::vector< Vector3 > Eigenvectors, Vector3 Eigenvalues, double lambda, double Mtot, double Sigma)
Push back all HP outputs for the different halos Push back onto the Vhp_ vectors the respective values.
Parameters:
HaloTypeIterator,: particle type in halo
J,: angular momentum
Eigenvectors
Eigenvalues
lambda,: dimensionless spin parameter, between 0 (no ordered rotation) to 0.425 (razor-thin, cold, exponential disk)
Mtot,: total mass
Sigma,: velocity dispersion
Definition at line 283 of file bu_AnalyzeSnap_Halo2.cpp.
References Vhp_Eigenvalues(), Vhp_EVa(), Vhp_EVb(), Vhp_EVc(), Vhp_J(), Vhp_LambdaPrime(), Vhp_Mass(), and Vhp_Sigma().
void ReadDataBlocks (std::string SnapshotFilename, int TotalNOParticles, int *& id, real *& pos, real *& vel, real *& mass)
Read snapshot data.
Fill in all information from snapshot data file (id, pos, vel, mass)
Parameters:
SnapshotFilename is string
id is int &
pos is double & (3d)
vel is double & (3d)
mass is double & (1d)
Definition at line 230 of file bu_AnalyzeSnap_Halo2.cpp.
References read_gadget_1(), and read_gadget_3().
void ReadSnapParticlesBunch (std::ifstream & SnapshotParticles, unsigned HaloPopulation, unsigned *& ParticleIndexID, int *& ParticleIndexType)
Read a halo full of snapshot particles from ahf_out_particles Read in a slab of HaloPopulation particles.
Parameters:
SnapshotParticles,: ifstream of ahf_out_particles
HaloPopulation,: int of particles in this halo
ParticleIndexID,: holds the output, all identifiers
ParticleIndexType,: holds the output, all types, in accordance with ParticleIndexID
Definition at line 306 of file bu_AnalyzeSnap_Halo2.cpp.
Referenced by GenerateHalo2().
void Storeahf (int isnap)
Definition at line 103 of file bu_AnalyzeSnap_Halo2.cpp.
References Folder(), Snaps(), Vahf_Ekin, Vahf_Epot, Vahf_EVa, Vahf_EVb, Vahf_EVc, Vahf_EW, Vahf_J, Vahf_npart, Vahf_nvpart, Vahf_ovdens, Vahf_sigV, and Vahf_xc.
VecVecDouble Vhp_Eigenvalues (HaloTypeTotal)
VecVecDouble Vhp_EVa (HaloTypeTotal)
VecVecDouble Vhp_EVb (HaloTypeTotal)
VecVecDouble Vhp_EVc (HaloTypeTotal)
std::vector< std::vector < unsigned > > Vhp_HaloParticlesTypesCount (HaloTypeTotal)
VecVecDouble Vhp_J (HaloTypeTotal)
VecVecDouble Vhp_LambdaPrime (HaloTypeTotal)
VecVecDouble Vhp_Mass (HaloTypeTotal)
VecVecDouble Vhp_Sigma (HaloTypeTotal)
void WriteHDF5 (std::string filename, double Boxsize, double Redshift, double HaloTotCount)
write all calculated properties into a HDF5 file This function takes all publicly known variables and writes them to disk
Parameters:
filename string of the HDF5 output file
Boxsize boxsize of simulation volume in Mpc/h
Redshift simulation snapshot redshift
HaloTotCount total number of halos
Definition at line 159 of file bu_AnalyzeSnap_Halo2.cpp.
References HaloTypeTotal, HDFCreateFile(), HDFCreateGroup(), HDFWriteDataset(), HDFWriteDatasetVector(), HDFWriteGroupAttribute(), Vahf_Ekin, Vahf_Epot, Vahf_EVa, Vahf_EVb, Vahf_EVc, Vahf_EW, Vahf_J, Vahf_npart, Vahf_nvpart, Vahf_ovdens, Vahf_sigV, Vahf_xc, Vhp_Eigenvalues(), Vhp_EVa(), Vhp_EVb(), Vhp_EVc(), Vhp_HaloParticlesCount, Vhp_HaloParticlesTypesCount(), Vhp_J(), Vhp_LambdaPrime(), Vhp_Mass(), Vhp_Mvir, Vhp_PosCM, Vhp_PosMB, Vhp_Rvir, Vhp_Sigma(), and Vhp_VelCM.
Variable Documentation
const double h = 0.7
Definition at line 58 of file bu_AnalyzeSnap_Halo2.cpp.
const int HaloTypeTotal = 4
Definition at line 54 of file bu_AnalyzeSnap_Halo2.cpp.
const double Omega_M = 0.3
Definition at line 57 of file bu_AnalyzeSnap_Halo2.cpp.
const int ParticleTypeTotal = 6
Definition at line 55 of file bu_AnalyzeSnap_Halo2.cpp.
double rhobox = 0.0
Definition at line 61 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_Ekin
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_Epot
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_EVa
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_EVb
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_EVc
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_EW
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_J
Definition at line 75 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_npart
Definition at line 75 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_nvpart
Definition at line 75 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_ovdens
Definition at line 75 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_sigV
Definition at line 75 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vahf_xc
Definition at line 76 of file bu_AnalyzeSnap_Halo2.cpp.
std::vector< unsigned > Vhp_HaloParticlesCount
Definition at line 72 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vhp_Mvir
Definition at line 67 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vhp_PosCM
Definition at line 67 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vhp_PosMB
Definition at line 67 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vhp_Rvir
Definition at line 67 of file bu_AnalyzeSnap_Halo2.cpp.
VecDouble Vhp_VelCM
Definition at line 67 of file bu_AnalyzeSnap_Halo2.cpp.