HResults Class Reference
#include <HResults.h>
Public Member Functions
HResults ()
~HResults ()
void setNtot (int ntot)
void setMtot (real Mtot)
void setRtot (real Rtot)
void setMvir (real Mvir)
void setRvir (real Rvir)
void setXCM (Vector3 xcm)
void setVCM (Vector3 vcm)
void setXMB (Vector3 xmb)
void setVMB (Vector3 vmb)
void setNpart (int npart, int type)
void setMpart (real mpart, int type)
void setLambda (real lambda, int type)
void setSigma (real sigma, int type)
void setJ (Vector3 J, int type)
void setE (Eigensystem3 E, int type)
std::string toString ()
output a HResult as string concatenate first all global values, then all halo type specific properties
Detailed Description
Definition at line 35 of file HResults.h.
Constructor & Destructor Documentation
HResults::HResults ()
Definition at line 33 of file HResults.cpp.
HResults::~HResults ()
Definition at line 37 of file HResults.cpp.
Member Function Documentation
void HResults::setE (Eigensystem3 E, int type)
Definition at line 112 of file HResults.cpp.
Referenced by Output::fillHRtype().
void HResults::setJ (Vector3 J, int type)
Definition at line 97 of file HResults.cpp.
Referenced by Output::fillHRtype().
void HResults::setLambda (real lambda, int type)
Definition at line 102 of file HResults.cpp.
Referenced by Output::fillHRtype().
void HResults::setMpart (real mpart, int type)
Definition at line 92 of file HResults.cpp.
Referenced by Output::fillHRtype().
void HResults::setMtot (real Mtot)
Definition at line 47 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setMvir (real Mvir)
Definition at line 57 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setNpart (int npart, int type)
Definition at line 87 of file HResults.cpp.
Referenced by Output::fillHRtype().
void HResults::setNtot (int ntot)
Definition at line 42 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setRtot (real Rtot)
Definition at line 52 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setRvir (real Rvir)
Definition at line 62 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setSigma (real sigma, int type)
Definition at line 107 of file HResults.cpp.
Referenced by Output::fillHRtype().
void HResults::setVCM (Vector3 vcm)
Definition at line 72 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setVMB (Vector3 vmb)
Definition at line 82 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setXCM (Vector3 xcm)
Definition at line 67 of file HResults.cpp.
Referenced by Output::fillHRglobal().
void HResults::setXMB (Vector3 xmb)
Definition at line 77 of file HResults.cpp.
Referenced by Output::fillHRglobal().
std::string HResults::toString (void)
output a HResult as string concatenate first all global values, then all halo type specific properties
Definition at line 121 of file HResults.cpp.
References HTotal, Eigensystem3::toString(), and Vector3::toString().
The documentation for this class was generated from the following files:
HResults.h
HResults.cpp