Distance Class Reference
#include <Distance.h>
Public Member Functions
Distance (real r, unsigned i)
Distance (const Distance &d)
bool operator< (const Distance &d) const
real getr (void) const
unsigned geti (void) const
Detailed Description
Definition at line 6 of file Distance.h.
Constructor & Destructor Documentation
Distance::Distance (real r, unsigned i)
Definition at line 4 of file Distance.cpp.
Distance::Distance (const Distance & d)
Definition at line 9 of file Distance.cpp.
References geti(), and getr().
Member Function Documentation
unsigned Distance::geti (void) const
Definition at line 25 of file Distance.cpp.
Referenced by Distance().
real Distance::getr (void) const
Definition at line 20 of file Distance.cpp.
Referenced by Distance(), and operator<().
bool Distance::operator< (const Distance & d) const
Definition at line 15 of file Distance.cpp.
References getr().
The documentation for this class was generated from the following files:
Distance.h
Distance.cpp