Cosmology Class Reference
#include <Cosmology.h>
Public Member Functions
Cosmology ()
Cosmology (real H0)
Cosmology (real OmegaM, real OmegaR, real OmegaL)
Cosmology (real H0, real OmegaM, real OmegaR, real OmegaL)
void setH0 (real H0)
real getH0 ()
void setG (real G)
real getG ()
void setTarkinOmega ()
void setOmegaL (real OmegaL)
real getOmegaL ()
void setOmegaM (real OmegaM)
real getOmegaM ()
void setOmegaR (real OmegaR)
real getOmegaR ()
real getOmegaK ()
Detailed Description
Definition at line 11 of file Cosmology.h.
Constructor & Destructor Documentation
Cosmology::Cosmology ()
Definition at line 4 of file Cosmology.cpp.
Cosmology::Cosmology (real H0)
Definition at line 10 of file Cosmology.cpp.
Cosmology::Cosmology (real OmegaM, real OmegaR, real OmegaL)
Definition at line 16 of file Cosmology.cpp.
Cosmology::Cosmology (real H0, real OmegaM, real OmegaR, real OmegaL)
Definition at line 25 of file Cosmology.cpp.
Member Function Documentation
real Cosmology::getG ()
Definition at line 81 of file Cosmology.cpp.
Referenced by Simulation::getG().
real Cosmology::getH0 ()
Definition at line 71 of file Cosmology.cpp.
Referenced by Simulation::getH0().
real Cosmology::getOmegaK ()
Definition at line 119 of file Cosmology.cpp.
Referenced by Simulation::getOmegaK().
real Cosmology::getOmegaL ()
Definition at line 92 of file Cosmology.cpp.
Referenced by Simulation::getOmegaL().
real Cosmology::getOmegaM ()
Definition at line 103 of file Cosmology.cpp.
Referenced by Simulation::getOmegaM().
real Cosmology::getOmegaR ()
Definition at line 114 of file Cosmology.cpp.
Referenced by Simulation::getOmegaR().
void Cosmology::setG (real G)
Definition at line 76 of file Cosmology.cpp.
void Cosmology::setH0 (real H0)
Definition at line 66 of file Cosmology.cpp.
void Cosmology::setOmegaL (real OmegaL)
Definition at line 86 of file Cosmology.cpp.
void Cosmology::setOmegaM (real OmegaM)
Definition at line 97 of file Cosmology.cpp.
void Cosmology::setOmegaR (real OmegaR)
Definition at line 108 of file Cosmology.cpp.
void Cosmology::setTarkinOmega ()
Definition at line 53 of file Cosmology.cpp.
Referenced by Simulation::setTarkinOmega().
The documentation for this class was generated from the following files:
Cosmology.h
Cosmology.cpp