Output Class Reference
#include <Output.h>
Public Member Functions
Output ()
Output (Simulation sim)
~Output ()
void getAR (void)
void writeAR (void)
void fillHRglobal (int Ntot, real Mtot, real Rtot, real Mvir, real Rvir, Vector3 xcm, Vector3 vcm, Vector3 xmb, Vector3 vmb)
void fillHRtype (int type, int npart, real mpart, real lambda, real sigma, Vector3 J, Eigensystem3 E)
void appendHR (void)
void writeHR (void)
void writeHRstripped (void)
Detailed Description
Definition at line 35 of file Output.h.
Constructor & Destructor Documentation
Output::Output (void)
Definition at line 34 of file Output.cpp.
Output::Output (Simulation sim)
Definition at line 38 of file Output.cpp.
Output::~Output (void)
Definition at line 42 of file Output.cpp.
Member Function Documentation
void Output::appendHR (void)
Definition at line 138 of file Output.cpp.
Referenced by AnalyzeSnap().
void Output::fillHRglobal (int Ntot, real Mtot, real Rtot, real Mvir, real Rvir, Vector3 xcm, Vector3 vcm, Vector3 xmb, Vector3 vmb)
Definition at line 113 of file Output.cpp.
References HResults::setMtot(), HResults::setMvir(), HResults::setNtot(), HResults::setRtot(), HResults::setRvir(), HResults::setVCM(), HResults::setVMB(), HResults::setXCM(), and HResults::setXMB().
Referenced by AnalyzeSnap().
void Output::fillHRtype (int type, int npart, real mpart, real lambda, real sigma, Vector3 J, Eigensystem3 E)
Definition at line 127 of file Output.cpp.
References HResults::setE(), HResults::setJ(), HResults::setLambda(), HResults::setMpart(), HResults::setNpart(), and HResults::setSigma().
Referenced by AnalyzeSnap().
void Output::getAR (void)
Definition at line 48 of file Output.cpp.
References Folder(), Simulation::getIsnap(), Simulation::getNhalo(), and Snaps().
Referenced by AOutput().
void Output::writeAR (void)
Definition at line 101 of file Output.cpp.
References Folder(), Simulation::getIsnap(), Simulation::getNhalo(), and Snaps().
Referenced by AOutput().
void Output::writeHR (void)
Definition at line 143 of file Output.cpp.
References Folder(), Simulation::getBoxlength(), Simulation::getIsnap(), Simulation::getNhalo(), Simulation::getZsnap(), and Snaps().
Referenced by AnalyzeSnap().
void Output::writeHRstripped (void)
Definition at line 158 of file Output.cpp.
References Folder(), Simulation::getIsnap(), Simulation::getNhalo(), and Snaps().
Referenced by AnalyzeSnap().
The documentation for this class was generated from the following files:
Output.h
Output.cpp