Array3 Class Reference
#include <Array3.h>
Public Member Functions
Array3 (void)
Array3 (float *dataptr, int nx, int ny, int nz)
Array3 (int nx, int ny, int nz)
~Array3 ()
Array3 * operator= (Array3 *a)
int getNx ()
int getNy ()
int getNz ()
float * getData ()
bool getRealContainer ()
float getValue (int ix, int iy, int iz)
void setValue (int ix, int iy, int iz, float val)
void addValue (int ix, int iy, int iz, float val)
int get_size (void)
void recreate (int nx, int ny, int nz)
Protected Attributes
float * data_
int nx_
int ny_
int nz_
bool RealContainer_
Detailed Description
Definition at line 31 of file Array3.h.
Constructor & Destructor Documentation
Array3::Array3 (void)
Definition at line 30 of file Array3.cpp.
References data_, nx_, ny_, nz_, and RealContainer_.
Array3::Array3 (float * dataptr, int nx, int ny, int nz)
Definition at line 38 of file Array3.cpp.
References data_, nx_, ny_, nz_, and RealContainer_.
Array3::Array3 (int nx, int ny, int nz)
Definition at line 47 of file Array3.cpp.
References data_, nx_, ny_, nz_, and RealContainer_.
Array3::~Array3 ()
Definition at line 59 of file Array3.cpp.
References data_, and RealContainer_.
Member Function Documentation
void Array3::addValue (int ix, int iy, int iz, float val)
Definition at line 93 of file Array3.cpp.
References data_, ny_, and nz_.
Referenced by ScalarField::put_CIC().
int Array3::get_size (void)
Definition at line 99 of file Array3.cpp.
References nx_, ny_, and nz_.
float* Array3::getData () [inline]
Definition at line 49 of file Array3.h.
References data_.
Referenced by operator=().
int Array3::getNx () [inline]
Definition at line 46 of file Array3.h.
References nx_.
Referenced by operator=().
int Array3::getNy () [inline]
Definition at line 47 of file Array3.h.
References ny_.
Referenced by operator=().
int Array3::getNz () [inline]
Definition at line 48 of file Array3.h.
References nz_.
Referenced by operator=().
bool Array3::getRealContainer () [inline]
Definition at line 50 of file Array3.h.
References RealContainer_.
Referenced by operator=().
float Array3::getValue (int ix, int iy, int iz)
Definition at line 82 of file Array3.cpp.
References data_, ny_, and nz_.
Referenced by ScalarField::getValue(), and main().
Array3 * Array3::operator= (Array3 * a)
Definition at line 66 of file Array3.cpp.
References data_, getData(), getNx(), getNy(), getNz(), getRealContainer(), nx_, ny_, nz_, and RealContainer_.
void Array3::recreate (int nx, int ny, int nz)
Definition at line 104 of file Array3.cpp.
References data_, nx_, ny_, nz_, and RealContainer_.
Referenced by ScalarField::recreate().
void Array3::setValue (int ix, int iy, int iz, float val)
Definition at line 87 of file Array3.cpp.
References data_, ny_, and nz_.
Referenced by main(), ScalarField::put_CIC(), ScalarField::setValue(), and ScalarField::test().
Field Documentation
float* Array3::data_ [protected]
Definition at line 33 of file Array3.h.
Referenced by addValue(), Array3(), getData(), getValue(), operator=(), recreate(), setValue(), and ~Array3().
int Array3::nx_ [protected]
Definition at line 34 of file Array3.h.
Referenced by Array3(), get_size(), getNx(), operator=(), and recreate().
int Array3::ny_ [protected]
Definition at line 34 of file Array3.h.
Referenced by addValue(), Array3(), get_size(), getNy(), getValue(), operator=(), recreate(), and setValue().
int Array3::nz_ [protected]
Definition at line 34 of file Array3.h.
Referenced by addValue(), Array3(), get_size(), getNz(), getValue(), operator=(), recreate(), and setValue().
bool Array3::RealContainer_ [protected]
Definition at line 35 of file Array3.h.
Referenced by Array3(), getRealContainer(), operator=(), recreate(), and ~Array3().
The documentation for this class was generated from the following files:
Array3.h
Array3.cpp