PseudoBody Class Reference
#include <OctTree.h>
Public Member Functions
PseudoBody (void)
PseudoBody (real mass_, real x_, real y_, real z_)
PseudoBody (const std::vector< PseudoBody > &Bodies)
PseudoBody (const PseudoBody &b)
real getx (void) const
real gety (void) const
real getz (void) const
real getmass (void) const
real getxx (void) const
real getyy (void) const
real getzz (void) const
real getxy (void) const
real getyx (void) const
real getxz (void) const
real getzx (void) const
real getyz (void) const
real getzy (void) const
Protected Attributes
real mass
real x
real y
real z
real xx
real yy
real zz
real xy
real xz
real yz
Detailed Description
Definition at line 122 of file OctTree.h.
Constructor & Destructor Documentation
PseudoBody::PseudoBody (void) [inline]
Definition at line 130 of file OctTree.h.
PseudoBody::PseudoBody (real mass_, real x_, real y_, real z_) [inline]
Definition at line 133 of file OctTree.h.
PseudoBody::PseudoBody (const std::vector< PseudoBody > & Bodies) [inline]
Definition at line 137 of file OctTree.h.
References mass, x, xx, xy, xz, y, yy, yz, z, and zz.
PseudoBody::PseudoBody (const PseudoBody & b) [inline]
Definition at line 174 of file OctTree.h.
Member Function Documentation
real PseudoBody::getmass (void) const [inline]
Definition at line 190 of file OctTree.h.
References mass.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getx (void) const [inline]
Definition at line 180 of file OctTree.h.
References x.
Referenced by kDTreeNode::partition(), OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getxx (void) const [inline]
Definition at line 194 of file OctTree.h.
References xx.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getxy (void) const [inline]
Definition at line 203 of file OctTree.h.
References xy.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getxz (void) const [inline]
Definition at line 209 of file OctTree.h.
References xz.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::gety (void) const [inline]
Definition at line 183 of file OctTree.h.
References y.
Referenced by kDTreeNode::partition(), OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getyx (void) const [inline]
Definition at line 206 of file OctTree.h.
References xy.
real PseudoBody::getyy (void) const [inline]
Definition at line 197 of file OctTree.h.
References yy.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getyz (void) const [inline]
Definition at line 215 of file OctTree.h.
References yz.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getz (void) const [inline]
Definition at line 186 of file OctTree.h.
References z.
Referenced by kDTreeNode::partition(), OctTreeNode::traverse(), and kDTreeNode::traverse().
real PseudoBody::getzx (void) const [inline]
Definition at line 212 of file OctTree.h.
References xz.
real PseudoBody::getzy (void) const [inline]
Definition at line 218 of file OctTree.h.
References yz.
real PseudoBody::getzz (void) const [inline]
Definition at line 200 of file OctTree.h.
References zz.
Referenced by OctTreeNode::traverse(), and kDTreeNode::traverse().
Field Documentation
real PseudoBody::mass [protected]
Definition at line 124 of file OctTree.h.
Referenced by getmass(), and PseudoBody().
real PseudoBody::x [protected]
Definition at line 125 of file OctTree.h.
Referenced by getx(), and PseudoBody().
real PseudoBody::xx [protected]
Definition at line 127 of file OctTree.h.
Referenced by getxx(), and PseudoBody().
real PseudoBody::xy [protected]
Definition at line 127 of file OctTree.h.
Referenced by getxy(), getyx(), and PseudoBody().
real PseudoBody::xz [protected]
Definition at line 127 of file OctTree.h.
Referenced by getxz(), getzx(), and PseudoBody().
real PseudoBody::y [protected]
Definition at line 125 of file OctTree.h.
Referenced by gety(), and PseudoBody().
real PseudoBody::yy [protected]
Definition at line 127 of file OctTree.h.
Referenced by getyy(), and PseudoBody().
real PseudoBody::yz [protected]
Definition at line 127 of file OctTree.h.
Referenced by getyz(), getzy(), and PseudoBody().
real PseudoBody::z [protected]
Definition at line 125 of file OctTree.h.
Referenced by getz(), and PseudoBody().
real PseudoBody::zz [protected]
Definition at line 127 of file OctTree.h.
Referenced by getzz(), and PseudoBody().
The documentation for this class was generated from the following file:
OctTree.h