Halo Class Reference
#include <Halo.h>
Public Member Functions
Halo ()
~Halo ()
Halo (Simulation sim, real *pos, real *vel, real *mass, int *type, unsigned npart)
real getMtot ()
real getRtot ()
real getMvir ()
real getRvir ()
Vector3 getXCM ()
Vector3 getVCM ()
Vector3 getXMB ()
Vector3 getVMB ()
int calcNpart (int htype)
return number of particles of a given halo type
real calcMpart (int htype)
return mass of particles of a given halo type
real calcSigma (int htype)
calculate velocity dispersion sigma^2 = mean(v^2) - mean(v)^2
real calcLambda (int htype)
computes the simplified spin parameter lambda prime computes the halo spin parameter lambda' (Bullock et al. 2001). assumption: POS AND VEL CENTERED ON REFERENCE POINT (centerCM, centerMB)
Vector3 calcJ (int htype)
calculate angular momentum Angular momentum without considering Hubble flow (ASS: too short scales)
Eigensystem3 calcShape (int htype)
calculate halo shape determine inertia tensor of all particles of a given type, search eigensystem
Detailed Description
Definition at line 26 of file Halo.h.
Constructor & Destructor Documentation
Halo::Halo ()
Definition at line 36 of file Halo.cpp.
Halo::~Halo ()
Definition at line 40 of file Halo.cpp.
Halo::Halo (Simulation sim, real * pos, real * vel, real * mass, int * type, unsigned npart)
Definition at line 44 of file Halo.cpp.
References Simulation::getRhobox().
Member Function Documentation
Vector3 Halo::calcJ (int htype)
calculate angular momentum Angular momentum without considering Hubble flow (ASS: too short scales)
Parameters
htype,: int
Returns
J: Vector3
Definition at line 659 of file Halo.cpp.
References Simulation::getAsnap().
Referenced by AnalyzeSnap().
real Halo::calcLambda (int htype)
computes the simplified spin parameter lambda prime computes the halo spin parameter lambda' (Bullock et al. 2001). assumption: POS AND VEL CENTERED ON REFERENCE POINT (centerCM, centerMB)
Parameters
htype,: int
Returns
lambda'
Definition at line 609 of file Halo.cpp.
References Simulation::getAsnap(), Simulation::getG(), and Vector3::norm().
Referenced by AnalyzeSnap().
real Halo::calcMpart (int htype)
return mass of particles of a given halo type
Parameters
htype,: int
Returns
total mass of htype particles
Definition at line 542 of file Halo.cpp.
Referenced by AnalyzeSnap().
int Halo::calcNpart (int htype)
return number of particles of a given halo type
Parameters
htype,: int
Returns
total number of htype particles
Definition at line 526 of file Halo.cpp.
Referenced by AnalyzeSnap().
Eigensystem3 Halo::calcShape (int htype)
calculate halo shape determine inertia tensor of all particles of a given type, search eigensystem
Parameters
htype,: int
Definition at line 692 of file Halo.cpp.
References Eigensystem3::calcEV(), Eigensystem3::normalize(), and Matrix33::set_diag().
Referenced by AnalyzeSnap().
real Halo::calcSigma (int htype)
calculate velocity dispersion sigma^2 = mean(v^2) - mean(v)^2
Parameters
htype,: int
Returns
sigma: real
Definition at line 560 of file Halo.cpp.
Referenced by AnalyzeSnap().
real Halo::getMtot ()
Definition at line 279 of file Halo.cpp.
Referenced by AnalyzeSnap().
real Halo::getMvir ()
Definition at line 289 of file Halo.cpp.
Referenced by AnalyzeSnap().
real Halo::getRtot ()
Definition at line 284 of file Halo.cpp.
Referenced by AnalyzeSnap().
real Halo::getRvir ()
Definition at line 294 of file Halo.cpp.
Referenced by AnalyzeSnap().
Vector3 Halo::getVCM ()
Definition at line 304 of file Halo.cpp.
Referenced by AnalyzeSnap().
Vector3 Halo::getVMB ()
Definition at line 314 of file Halo.cpp.
Referenced by AnalyzeSnap().
Vector3 Halo::getXCM ()
Definition at line 299 of file Halo.cpp.
Referenced by AnalyzeSnap().
Vector3 Halo::getXMB ()
Definition at line 309 of file Halo.cpp.
Referenced by AnalyzeSnap().
The documentation for this class was generated from the following files:
Halo.h
Halo.cpp