Matrix33 Class Reference
#include <Matrix33.h>
Public Member Functions
Matrix33 ()
Matrix33 (const Matrix33 &m)
~Matrix33 ()
double & operator() (int row, int col)
double operator() (int row, int col) const
Vector3 operator() (int col) const
Matrix33 & operator= (Matrix33 const &M)
Matrix33 & operator= (const double &x)
Vector3 operator[] (int col) const
Matrix33 & operator+= (const Matrix33 &m)
Matrix33 & operator-= (const Matrix33 &m)
Matrix33 operator* (const double &x) const
Matrix33 operator/ (const double &x) const
void set_diag (Vector3 diag)
void Jacobi (std::vector< real > &Eval, std::vector< Vector3 > &Evec, int &nrot)
void Eigen (std::vector< real > &Eval, std::vector< Vector3 > &Evec) const
double det (void) const
Vector3 get_invariants (std::vector< Vector3 > Evec) const
std::vector< Vector3 > toVecVector3 () const
Protected Attributes
double * data_
Detailed Description
Definition at line 45 of file Matrix33.h.
Constructor & Destructor Documentation
Matrix33::Matrix33 ()
Definition at line 41 of file Matrix33.cpp.
References data_.
Matrix33::Matrix33 (const Matrix33 & m)
Definition at line 45 of file Matrix33.cpp.
References data_.
Matrix33::~Matrix33 ()
Definition at line 51 of file Matrix33.cpp.
References data_.
Member Function Documentation
double Matrix33::det (void) const
Definition at line 172 of file Matrix33.cpp.
References Eigen().
void Matrix33::Eigen (std::vector< real > & Eval, std::vector< Vector3 > & Evec) const
Definition at line 148 of file Matrix33.cpp.
References data_.
Referenced by Eigensystem3::calcEV(), HaloProperties::ComputeMajorAxes(), HaloProperties::ComputeMajorAxesReduced(), det(), and get_invariants().
Vector3 Matrix33::get_invariants (std::vector< Vector3 > Evec) const
Definition at line 183 of file Matrix33.cpp.
References Eigen().
void Matrix33::Jacobi (std::vector< real > & Eval, std::vector< Vector3 > & Evec, int & nrot)
Definition at line 215 of file Matrix33.cpp.
References ROTATE().
Vector3 Matrix33::operator() (int col) const
Definition at line 69 of file Matrix33.cpp.
double Matrix33::operator() (int row, int col) const
Definition at line 63 of file Matrix33.cpp.
References data_.
double & Matrix33::operator() (int row, int col)
Definition at line 57 of file Matrix33.cpp.
References data_.
Matrix33 Matrix33::operator* (const double & x) const
Definition at line 121 of file Matrix33.cpp.
References data_.
Matrix33 & Matrix33::operator+= (const Matrix33 & m)
Definition at line 105 of file Matrix33.cpp.
References data_.
Matrix33 & Matrix33::operator-= (const Matrix33 & m)
Definition at line 113 of file Matrix33.cpp.
References data_.
Matrix33 Matrix33::operator/ (const double & x) const
Definition at line 130 of file Matrix33.cpp.
References data_.
Matrix33 & Matrix33::operator= (const double & x)
Definition at line 87 of file Matrix33.cpp.
References data_.
Matrix33 & Matrix33::operator= (Matrix33 const & M)
Definition at line 78 of file Matrix33.cpp.
References data_.
Vector3 Matrix33::operator[] (int col) const
Definition at line 96 of file Matrix33.cpp.
References data_.
void Matrix33::set_diag (Vector3 diag)
Definition at line 140 of file Matrix33.cpp.
Referenced by Halo::calcShape().
std::vector< Vector3 > Matrix33::toVecVector3 () const
Definition at line 301 of file Matrix33.cpp.
Field Documentation
double* Matrix33::data_ [protected]
Definition at line 47 of file Matrix33.h.
Referenced by Eigen(), Matrix33(), operator()(), operator*(), operator+=(), operator-=(), operator/(), operator=(), operator[](), and ~Matrix33().
The documentation for this class was generated from the following files:
Matrix33.h
Matrix33.cpp