Simulation Class Reference
#include <Simulation.h>
Public Member Functions
Simulation ()
Simulation (Simulation &sim)
~Simulation ()
void setCosmology (Cosmology c)
void setIsnap (int isnap)
void setAsnap (real asnap)
void setZsnap (real zsnap)
void setNhalo (int nhalo)
void setMass (real mass)
void setTarkinOmega ()
void setBoxlength (real boxlength)
int getIsnap ()
real getAsnap ()
real getZsnap ()
int getNhalo ()
real getMass ()
real getBoxlength ()
real getRhobox ()
real getH0 ()
real getG ()
real getOmegaL ()
real getOmegaM ()
real getOmegaR ()
real getOmegaK ()
Detailed Description
Definition at line 7 of file Simulation.h.
Constructor & Destructor Documentation
Simulation::Simulation ()
Definition at line 13 of file Simulation.cpp.
Simulation::Simulation (Simulation & sim)
Definition at line 18 of file Simulation.cpp.
Simulation::~Simulation ()
Definition at line 22 of file Simulation.cpp.
Member Function Documentation
real Simulation::getAsnap ()
Definition at line 101 of file Simulation.cpp.
Referenced by Halo::calcJ(), and Halo::calcLambda().
real Simulation::getBoxlength ()
Definition at line 121 of file Simulation.cpp.
Referenced by Output::writeHR().
real Simulation::getG ()
Definition at line 136 of file Simulation.cpp.
References Cosmology::getG().
Referenced by Halo::calcLambda().
real Simulation::getH0 ()
Definition at line 131 of file Simulation.cpp.
References Cosmology::getH0().
int Simulation::getIsnap ()
Definition at line 96 of file Simulation.cpp.
Referenced by Output::getAR(), Output::writeAR(), Output::writeHR(), and Output::writeHRstripped().
real Simulation::getMass ()
Definition at line 116 of file Simulation.cpp.
int Simulation::getNhalo ()
Definition at line 111 of file Simulation.cpp.
Referenced by Output::getAR(), Output::writeAR(), Output::writeHR(), and Output::writeHRstripped().
real Simulation::getOmegaK ()
Definition at line 156 of file Simulation.cpp.
References Cosmology::getOmegaK().
real Simulation::getOmegaL ()
Definition at line 141 of file Simulation.cpp.
References Cosmology::getOmegaL().
real Simulation::getOmegaM ()
Definition at line 146 of file Simulation.cpp.
References Cosmology::getOmegaM().
real Simulation::getOmegaR ()
Definition at line 151 of file Simulation.cpp.
References Cosmology::getOmegaR().
real Simulation::getRhobox ()
Definition at line 126 of file Simulation.cpp.
Referenced by Halo::Halo().
real Simulation::getZsnap ()
Definition at line 106 of file Simulation.cpp.
Referenced by Output::writeHR().
void Simulation::setAsnap (real asnap)
Definition at line 43 of file Simulation.cpp.
void Simulation::setBoxlength (real boxlength)
Definition at line 66 of file Simulation.cpp.
Referenced by AnalyzeSnap().
void Simulation::setCosmology (Cosmology c)
Definition at line 27 of file Simulation.cpp.
void Simulation::setIsnap (int isnap)
Definition at line 38 of file Simulation.cpp.
Referenced by AnalyzeSnap(), and AOutput().
void Simulation::setMass (real mass)
Definition at line 60 of file Simulation.cpp.
Referenced by AnalyzeSnap().
void Simulation::setNhalo (int nhalo)
Definition at line 55 of file Simulation.cpp.
Referenced by AnalyzeSnap().
void Simulation::setTarkinOmega ()
Definition at line 33 of file Simulation.cpp.
References Cosmology::setTarkinOmega().
Referenced by AnalyzeSnap().
void Simulation::setZsnap (real zsnap)
Definition at line 49 of file Simulation.cpp.
Referenced by AnalyzeSnap().
The documentation for this class was generated from the following files:
Simulation.h
Simulation.cpp