Vector3 Class Reference
#include <Vector3.h>
Public Member Functions
Vector3 (void)
Vector3 (const Vector3 &v)
Vector3 (real x)
Vector3 (real x, real y, real z)
template<typename real_t >
Vector3 (const real_t *x0)
~Vector3 ()
Vector3 & operator= (const Vector3 &b)
Vector3 & operator= (const real &x)
Vector3 & operator- (void)
Vector3 operator+ (const Vector3 &x) const
Vector3 operator- (const Vector3 &x) const
Vector3 operator* (const real &x)
Vector3 operator/ (const real &x)
Vector3 & operator+= (const Vector3 &x)
Vector3 & operator-= (const Vector3 &x)
Vector3 & operator*= (const real &x)
Vector3 & operator/= (const real &x)
real & operator() (const unsigned i)
real operator* (const Vector3 &vb) const
Vector3 operator^ (const Vector3 &vb) const
real norm (void) const
real norm2 (void) const
Vector3 & normalize (void)
std::string toString (void)
Protected Attributes
real * data_
Detailed Description
Definition at line 63 of file Vector3.h.
Constructor & Destructor Documentation
Vector3::Vector3 (void)
Definition at line 61 of file Vector3.cpp.
References data_.
Vector3::Vector3 (const Vector3 & v)
Definition at line 67 of file Vector3.cpp.
References data_.
Vector3::Vector3 (real x)
Definition at line 73 of file Vector3.cpp.
References data_.
Vector3::Vector3 (real x, real y, real z)
Definition at line 79 of file Vector3.cpp.
References data_.
template<typename real_t > Vector3::Vector3 (const real_t * x0) [inline]
Definition at line 87 of file Vector3.cpp.
References data_.
Vector3::~Vector3 ()
Definition at line 93 of file Vector3.cpp.
References data_.
Member Function Documentation
real Vector3::norm (void) const
Definition at line 220 of file Vector3.cpp.
Referenced by Halo::calcLambda(), HaloProperties::ComputeAngularMomentum(), HaloProperties::ComputeLambdaPrime(), and normalize().
real Vector3::norm2 (void) const
Definition at line 226 of file Vector3.cpp.
Referenced by normalize().
Vector3 & Vector3::normalize (void)
Definition at line 232 of file Vector3.cpp.
References norm(), and norm2().
real & Vector3::operator() (const unsigned i)
Definition at line 191 of file Vector3.cpp.
References data_.
real Vector3::operator* (const Vector3 & vb) const
Definition at line 198 of file Vector3.cpp.
References data_.
Vector3 Vector3::operator* (const real & x)
Definition at line 141 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator*= (const real & x)
Definition at line 175 of file Vector3.cpp.
References data_.
Vector3 Vector3::operator+ (const Vector3 & x) const
Definition at line 123 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator+= (const Vector3 & x)
Definition at line 159 of file Vector3.cpp.
References data_.
Vector3 Vector3::operator- (const Vector3 & x) const
Definition at line 132 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator- (void)
Definition at line 115 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator-= (const Vector3 & x)
Definition at line 167 of file Vector3.cpp.
References data_.
Vector3 Vector3::operator/ (const real & x)
Definition at line 150 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator/= (const real & x)
Definition at line 183 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator= (const real & x)
Definition at line 107 of file Vector3.cpp.
References data_.
Vector3 & Vector3::operator= (const Vector3 & b)
Definition at line 99 of file Vector3.cpp.
References data_.
Vector3 Vector3::operator^ (const Vector3 & vb) const
Definition at line 208 of file Vector3.cpp.
References data_.
std::string Vector3::toString (void)
Definition at line 247 of file Vector3.cpp.
References data_.
Referenced by HResults::toString(), and AResults::toString().
Field Documentation
real* Vector3::data_ [protected]
Definition at line 65 of file Vector3.h.
Referenced by operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator^(), toString(), Vector3(), and ~Vector3().
The documentation for this class was generated from the following files:
Vector3.h
Vector3.cpp