HaloProperties Class Reference
#include <HaloProperties.h>
Data Structures
struct Cosm
class Distance
Public Member Functions
HaloProperties (real *pPos, real *pVel, real *pMass, unsigned nPart, real zsnap)
void SetCosmology (real OmegaM0, real OmegaL0, real H0, real G)
real ComputeTotalMass (void)
real ComputeTotalMassExc (std::vector< bool > excluded)
void ComputeCM (real Boxlength, Vector3 &xcm)
void ComputeCMExc (real Boxlength, Vector3 &xcm, std::vector< bool > excluded)
void ComputeMB (real Boxlength, Vector3 &xmb)
void ComputeMBExc (real Boxlength, Vector3 &xmb, std::vector< bool > excluded)
void CenterOnCM (real Boxlength)
void CenterOnCMExc (real Boxlength, std::vector< bool > excluded)
real CenterOnMB (real Boxlength)
real CenterOnMB (real Boxlength, real &rmbcm, real &alpha)
void CenterOnCoord (real *xc, real Boxlength)
void AverageVel (const unsigned n, const real eps=0.0)
void ComputeCenterVel (Vector3 &vcm)
void ComputeCenterVelExc (Vector3 &vcm, std::vector< bool > excluded)
void CenterVel (void)
void CenterVelOn (real *vc)
void CenterVelExc (std::vector< bool > excluded)
void ComputeAngularMomentum (real &Jtot)
real ComputeAngularMomentum (Vector3 &J) const
void ComputeVelocityDispersion (real &Sigma)
void GetSortedDistances (std::vector< Distance > &dvec) const
void ComputeMajorAxes (Vector3 &Eigenvalues, std::vector< Vector3 > &Eigenvectors) const
void ComputeMajorAxesReduced (Vector3 &Eigenvalues, std::vector< Vector3 > &Eigenvectors) const
void ComputeShapeParameters (real &T, real &S) const
void ComputeVirialProperties200 (real rhobox, real &Mvir, real &Rvir) const
void ComputeVirialProperties200 (real rhobox, real &Mvir, real &Rvir, real &Vcmax) const
void ComputeVirialProperties200 (real rhobox, real &Mvir, real &Rvir, std::vector< Distance > &dvec) const
void ComputeVirialProperties200 (real rhobox, real &Mvir, real &Rvir, real &Vcmax, std::vector< Distance > &dvec) const
void ComputeVirialProperties (real rhobox, real &Mvir, real &Rvir) const
void ComputeVirialProperties (real rhobox, real &Mvir, real &Rvir, real &Vcmax) const
void ComputeVirialProperties (real rhobox, real &Mvir, real &Rvir, std::vector< Distance > &dvec) const
void ComputeVirialProperties (real rhobox, real &Mvir, real &Rvir, real &Vcmax, std::vector< Distance > &dvec) const
real ComputePoormanConcentration (real rhobox, real &R20, real &R80)
real ComputePoormanConcentration (real rhobox)
void ComputeLambdaPrime (real &lambda, real Mvir, real Rvir)
computes the simplified spin parameter lambda prime computes the lambda prime (Bullock et al. 2001). ASSUMES THAT COORDINATES AND VELOCITIES ARE CENTERED ON REFERENCE POINT. so center on center of mass or something.
real ComputeKineticEnergy (std::vector< real > &kin) const
real ComputeKineticEnergyNoHubble (std::vector< real > &kin) const
void ComputeKineticEnergyNoHubbleExc (std::vector< real > &kin, std::vector< bool > excluded) const
real ComputePotentialDirect (real plumsoft, std::vector< real > &phi) const
void ComputePotentialDirectExc (real plumsoft, std::vector< real > &phi, std::vector< bool > excluded) const
real ComputePotentialTree (real theta, real plumsoft, std::vector< real > &phi) const
void ComputePotentialTreeExc (real theta, real plumsoft, std::vector< real > &phi, std::vector< bool > excluded) const
std::vector< bool > CleanUnbound (real boxsize)
void CleanUnboundExc (real boxsize, std::vector< bool > &excluded)
void CleanUnboundSimple (real boxsize, std::vector< bool > &excluded)
int ComputeDensityProfile (real rhobox, unsigned n, std::vector< real > &r, std::vector< real > &rho, std::vector< real > &sigma_rho) const
int FitNFWProfile2 (real rhobox, unsigned n, real &fdeltac, real &fedeltac, real &frs, real &fers) const
int FitNFWProfile1 (real rhobox, unsigned n, real &frs, real &fers) const
int FitNFWProfile200 (real rhobox, unsigned n, real &frs, real &fers) const
Protected Attributes
real m_xcm [3]
real m_xmb [3]
real m_vcm [3]
real m_vmb [3]
real m_rmbcm
real * m_pPos
real * m_pVel
real * m_pMass
real m_mtot
unsigned m_nPart
real m_alpha
unsigned m_imostbound
Cosm m_Cosm
Detailed Description
Definition at line 47 of file HaloProperties.h.
Constructor & Destructor Documentation
HaloProperties::HaloProperties (real * pPos, real * pVel, real * pMass, unsigned nPart, real zsnap)
Definition at line 15 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, HaloProperties::Cosm::H0, m_Cosm, m_imostbound, m_mtot, m_nPart, m_pMass, m_pPos, m_pVel, m_vcm, m_vmb, m_xcm, m_xmb, HaloProperties::Cosm::OmegaL0, and HaloProperties::Cosm::OmegaM0.
Member Function Documentation
void HaloProperties::AverageVel (const unsigned n, const real eps = 0.0)
average the velocities of particles using ANN
Definition at line 325 of file HaloProperties.cpp.
References m_nPart, m_pMass, m_pPos, m_pVel, and SPHK3D().
void HaloProperties::CenterOnCM (real Boxlength)
centers on the CM obeying periodic boundary conditions. REQUIRES THAT THE EXTENSION OF THE OBJECT DO NOT EXCEED 0.25 OF THE BOX LENGTH.
Parameters
Boxlength the length of the simulation box
Returns
nothing, centers the coordinates on the CM and stores the CM
Definition at line 125 of file HaloProperties.cpp.
References m_mtot, m_nPart, m_pMass, m_pPos, and m_xcm.
Referenced by CleanUnboundSimple().
void HaloProperties::CenterOnCMExc (real Boxlength, std::vector< bool > excluded)
Definition at line 157 of file HaloProperties.cpp.
References m_nPart, m_pMass, m_pPos, and m_xcm.
Referenced by CleanUnboundExc().
void HaloProperties::CenterOnCoord (real * xc, real Boxlength)
centers all coordinates on specified point
Parameters
xc pointer to an array of three reals contain the point to be centered on
Boxlength size of simulation (cubic) box
Definition at line 314 of file HaloProperties.cpp.
References m_nPart, and m_pPos.
Referenced by CenterOnMB().
real HaloProperties::CenterOnMB (real Boxlength, real & rmbcm, real & alpha)
Center on Most Bound particle. CenterOnCM(Boxlength); CenterVel(); is needed before invoking CenterOnMB
Parameters
Boxlength
rmbcm
alpha
Returns
Definition at line 270 of file HaloProperties.cpp.
References CenterOnCoord(), ComputeKineticEnergyNoHubble(), ComputePotentialDirect(), ComputePotentialTree(), FORCE_DIRECT_TREE_SPLIT, m_alpha, m_imostbound, m_nPart, m_pPos, m_rmbcm, and m_xmb.
real HaloProperties::CenterOnMB (real Boxlength)
centers all coordinates on the MB obeying periodic boundary conditions ... centers on the MB obeying periodic boundary conditions. REQUIRES THAT THE EXTENSION OF THE OBJECT DOES NOT EXCEED 0.25 * BOX LENGTH.
Parameters
Boxlength
Returns
distance of mb from cm, centers the coordinates on the MB and stores the MB
Definition at line 257 of file HaloProperties.cpp.
void HaloProperties::CenterVel (void)
Definition at line 429 of file HaloProperties.cpp.
References m_mtot, m_nPart, m_pMass, m_pVel, and m_vcm.
Referenced by CleanUnboundSimple().
void HaloProperties::CenterVelExc (std::vector< bool > excluded)
Definition at line 459 of file HaloProperties.cpp.
References m_nPart, m_pMass, m_pVel, and m_vcm.
Referenced by CleanUnboundExc().
void HaloProperties::CenterVelOn (real * vc)
Definition at line 451 of file HaloProperties.cpp.
References m_nPart, m_pVel, and m_vcm.
std::vector< bool > HaloProperties::CleanUnbound (real boxsize)
Definition at line 1098 of file HaloProperties.cpp.
References CleanUnboundExc(), and m_nPart.
void HaloProperties::CleanUnboundExc (real boxsize, std::vector< bool > & excluded)
Definition at line 1106 of file HaloProperties.cpp.
References CenterOnCMExc(), CenterVelExc(), ComputeKineticEnergyNoHubbleExc(), ComputePotentialTreeExc(), and m_nPart.
Referenced by CleanUnbound().
void HaloProperties::CleanUnboundSimple (real boxsize, std::vector< bool > & excluded)
Definition at line 1170 of file HaloProperties.cpp.
References CenterOnCM(), CenterVel(), ComputeKineticEnergyNoHubbleExc(), ComputePotentialDirectExc(), and m_nPart.
real HaloProperties::ComputeAngularMomentum (Vector3 & J) const
computes the angular momentum in internal units. assumes that coordinates and velocities are centered on a reference point
Returns
real Jtot, total angular momentum
Definition at line 517 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, m_Cosm, m_nPart, m_pMass, m_pPos, m_pVel, and Vector3::norm().
void HaloProperties::ComputeAngularMomentum (real & Jtot)
computes the angular momentum in internal units. assumes that coordinates and velocities are centered on a reference point
Parameters
Jtot total angular momentum
Returns
void
Definition at line 492 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, m_Cosm, m_nPart, m_pMass, m_pPos, and m_pVel.
void HaloProperties::ComputeCenterVel (Vector3 & vcm)
Definition at line 392 of file HaloProperties.cpp.
References m_mtot, m_nPart, m_pMass, m_pVel, and m_vcm.
void HaloProperties::ComputeCenterVelExc (Vector3 & vcm, std::vector< bool > excluded)
Definition at line 408 of file HaloProperties.cpp.
References m_nPart, m_pMass, and m_pVel.
void HaloProperties::ComputeCM (real Boxlength, Vector3 & xcm)
Definition at line 68 of file HaloProperties.cpp.
References m_mtot, m_nPart, m_pMass, and m_pPos.
void HaloProperties::ComputeCMExc (real Boxlength, Vector3 & xcm, std::vector< bool > excluded)
Definition at line 93 of file HaloProperties.cpp.
References m_nPart, m_pMass, and m_pPos.
int HaloProperties::ComputeDensityProfile (real rhobox, unsigned n, std::vector< real > & r, std::vector< real > & rho, std::vector< real > & sigma_rho) const
Definition at line 1202 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, ComputeVirialProperties(), m_Cosm, m_nPart, and m_pMass.
Referenced by FitNFWProfile1(), FitNFWProfile2(), and FitNFWProfile200().
real HaloProperties::ComputeKineticEnergy (std::vector< real > & kin) const
Compute the kinetic energies for all particles
Parameters
kin vector to be filled with kin. energies
Returns
total kinetic energy
Definition at line 846 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::H0, m_Cosm, m_nPart, m_pMass, m_pPos, m_pVel, HaloProperties::Cosm::OmegaL0, and HaloProperties::Cosm::OmegaM0.
real HaloProperties::ComputeKineticEnergyNoHubble (std::vector< real > & kin) const
Computes the kinetic energy of all particles without Hubble flow.
Parameters
kin vector with kinetic energies
Returns
total kinetic energy
Definition at line 887 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, m_Cosm, m_nPart, m_pMass, and m_pVel.
Referenced by CenterOnMB(), ComputeMB(), and ComputeMBExc().
void HaloProperties::ComputeKineticEnergyNoHubbleExc (std::vector< real > & kin, std::vector< bool > excluded) const
Definition at line 924 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, m_Cosm, m_nPart, m_pMass, and m_pVel.
Referenced by CleanUnboundExc(), and CleanUnboundSimple().
void HaloProperties::ComputeLambdaPrime (real & lambda, real Mvir, real Rvir)
computes the simplified spin parameter lambda prime computes the lambda prime (Bullock et al. 2001). ASSUMES THAT COORDINATES AND VELOCITIES ARE CENTERED ON REFERENCE POINT. so center on center of mass or something.
Parameters
lambda storage for halo spin parameter
Mvir the virial mass is returned here
Rvir the virial radius is returned here
Returns
void
Definition at line 805 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, GetSortedDistances(), m_Cosm, m_nPart, m_pMass, m_pPos, m_pVel, and Vector3::norm().
void HaloProperties::ComputeMajorAxes (Vector3 & Eigenvalues, std::vector< Vector3 > & Eigenvectors) const
Definition at line 583 of file HaloProperties.cpp.
References Matrix33::Eigen(), m_mtot, m_nPart, m_pMass, and m_pPos.
Referenced by ComputeShapeParameters().
void HaloProperties::ComputeMajorAxesReduced (Vector3 & Eigenvalues, std::vector< Vector3 > & Eigenvectors) const
Definition at line 618 of file HaloProperties.cpp.
References Matrix33::Eigen(), m_imostbound, m_nPart, m_pMass, and m_pPos.
void HaloProperties::ComputeMB (real Boxlength, Vector3 & xmb)
Definition at line 197 of file HaloProperties.cpp.
References ComputeKineticEnergyNoHubble(), ComputePotentialDirect(), ComputePotentialTree(), FORCE_DIRECT_TREE_SPLIT, m_nPart, and m_pPos.
void HaloProperties::ComputeMBExc (real Boxlength, Vector3 & xmb, std::vector< bool > excluded)
Definition at line 224 of file HaloProperties.cpp.
References ComputeKineticEnergyNoHubble(), ComputePotentialDirect(), ComputePotentialTree(), FORCE_DIRECT_TREE_SPLIT, m_nPart, and m_pPos.
real HaloProperties::ComputePoormanConcentration (real rhobox)
Definition at line 789 of file HaloProperties.cpp.
References ComputePoormanConcentration().
real HaloProperties::ComputePoormanConcentration (real rhobox, real & R20, real & R80)
Definition at line 778 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, ComputeVirialProperties(), and m_Cosm.
Referenced by ComputePoormanConcentration().
real HaloProperties::ComputePotentialDirect (real plumsoft, std::vector< real > & phi) const
Computes the potential directly from particle positions and masses. Center on CM before invoking this routine
Parameters
plumsoft smoothing length
phi potential
Returns
total potential energy
Definition at line 940 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, m_Cosm, m_nPart, m_pMass, and m_pPos.
Referenced by CenterOnMB(), ComputeMB(), and ComputeMBExc().
void HaloProperties::ComputePotentialDirectExc (real plumsoft, std::vector< real > & phi, std::vector< bool > excluded) const
Definition at line 966 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, m_Cosm, m_nPart, m_pMass, and m_pPos.
Referenced by CleanUnboundSimple().
real HaloProperties::ComputePotentialTree (real theta, real plumsoft, std::vector< real > & phi) const
Definition at line 995 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, m_Cosm, m_nPart, m_pMass, m_pPos, and OctTreeNode::traverse().
Referenced by CenterOnMB(), ComputeMB(), and ComputeMBExc().
void HaloProperties::ComputePotentialTreeExc (real theta, real plumsoft, std::vector< real > & phi, std::vector< bool > excluded) const
Definition at line 1049 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, m_Cosm, m_nPart, m_pMass, m_pPos, and OctTreeNode::traverse().
Referenced by CleanUnboundExc().
void HaloProperties::ComputeShapeParameters (real & T, real & S) const
Definition at line 658 of file HaloProperties.cpp.
References ComputeMajorAxes().
real HaloProperties::ComputeTotalMass (void)
Definition at line 54 of file HaloProperties.cpp.
References m_mtot.
real HaloProperties::ComputeTotalMassExc (std::vector< bool > excluded)
Definition at line 59 of file HaloProperties.cpp.
References m_nPart, and m_pMass.
void HaloProperties::ComputeVelocityDispersion (real & Sigma)
computes the velocity dispersion (sigma) in internal units assumes that pos and vel be centered
Definition at line 546 of file HaloProperties.cpp.
References m_nPart, and m_pVel.
void HaloProperties::ComputeVirialProperties (real rhobox, real & Mvir, real & Rvir, real & Vcmax, std::vector< Distance > & dvec) const
Definition at line 728 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, GetSortedDistances(), m_Cosm, and m_pMass.
void HaloProperties::ComputeVirialProperties (real rhobox, real & Mvir, real & Rvir, std::vector< Distance > & dvec) const
Definition at line 761 of file HaloProperties.cpp.
References ComputeVirialProperties().
void HaloProperties::ComputeVirialProperties (real rhobox, real & Mvir, real & Rvir, real & Vcmax) const
Definition at line 766 of file HaloProperties.cpp.
References ComputeVirialProperties().
void HaloProperties::ComputeVirialProperties (real rhobox, real & Mvir, real & Rvir) const
Definition at line 771 of file HaloProperties.cpp.
Referenced by ComputeDensityProfile(), ComputePoormanConcentration(), ComputeVirialProperties(), and FitNFWProfile1().
void HaloProperties::ComputeVirialProperties200 (real rhobox, real & Mvir, real & Rvir, real & Vcmax, std::vector< Distance > & dvec) const
Definition at line 668 of file HaloProperties.cpp.
References HaloProperties::Cosm::asnap, HaloProperties::Cosm::G, GetSortedDistances(), m_Cosm, m_pMass, HaloProperties::Cosm::OmegaL0, and HaloProperties::Cosm::OmegaM0.
void HaloProperties::ComputeVirialProperties200 (real rhobox, real & Mvir, real & Rvir, std::vector< Distance > & dvec) const
Definition at line 715 of file HaloProperties.cpp.
References ComputeVirialProperties200().
void HaloProperties::ComputeVirialProperties200 (real rhobox, real & Mvir, real & Rvir, real & Vcmax) const
Definition at line 710 of file HaloProperties.cpp.
References ComputeVirialProperties200().
void HaloProperties::ComputeVirialProperties200 (real rhobox, real & Mvir, real & Rvir) const
Definition at line 720 of file HaloProperties.cpp.
Referenced by ComputeVirialProperties200(), and FitNFWProfile200().
int HaloProperties::FitNFWProfile1 (real rhobox, unsigned n, real & frs, real & fers) const
Definition at line 1345 of file HaloProperties.cpp.
References ComputeDensityProfile(), ComputeVirialProperties(), and NFW_fix_fit().
int HaloProperties::FitNFWProfile2 (real rhobox, unsigned n, real & fdeltac, real & fedeltac, real & frs, real & fers) const
Definition at line 1317 of file HaloProperties.cpp.
References ComputeDensityProfile(), and NFW_fit().
int HaloProperties::FitNFWProfile200 (real rhobox, unsigned n, real & frs, real & fers) const
Definition at line 1368 of file HaloProperties.cpp.
References ComputeDensityProfile(), ComputeVirialProperties200(), and NFW_fix_fit().
void HaloProperties::GetSortedDistances (std::vector< Distance > & dvec) const
Definition at line 568 of file HaloProperties.cpp.
References m_nPart, and m_pPos.
Referenced by ComputeLambdaPrime(), ComputeVirialProperties(), and ComputeVirialProperties200().
void HaloProperties::SetCosmology (real OmegaM0, real OmegaL0, real H0, real G = 43011.7902)
Set internal units and values for cosmological constants
Parameters
OmegaM0 fraction of mass density and critical density
OmegaL0 fraction of false vacuum density and critical density
H0 present day Hubble constant
G gravitation constant, in internal units
Definition at line 46 of file HaloProperties.cpp.
References HaloProperties::Cosm::G, HaloProperties::Cosm::H0, m_Cosm, HaloProperties::Cosm::OmegaL0, and HaloProperties::Cosm::OmegaM0.
Field Documentation
real HaloProperties::m_alpha [protected]
Definition at line 55 of file HaloProperties.h.
Referenced by CenterOnMB().
Cosm HaloProperties::m_Cosm [protected]
Definition at line 62 of file HaloProperties.h.
Referenced by ComputeAngularMomentum(), ComputeDensityProfile(), ComputeKineticEnergy(), ComputeKineticEnergyNoHubble(), ComputeKineticEnergyNoHubbleExc(), ComputeLambdaPrime(), ComputePoormanConcentration(), ComputePotentialDirect(), ComputePotentialDirectExc(), ComputePotentialTree(), ComputePotentialTreeExc(), ComputeVirialProperties(), ComputeVirialProperties200(), HaloProperties(), and SetCosmology().
unsigned HaloProperties::m_imostbound [protected]
Definition at line 56 of file HaloProperties.h.
Referenced by CenterOnMB(), ComputeMajorAxesReduced(), and HaloProperties().
real HaloProperties::m_mtot [protected]
Definition at line 52 of file HaloProperties.h.
Referenced by CenterOnCM(), CenterVel(), ComputeCenterVel(), ComputeCM(), ComputeMajorAxes(), ComputeTotalMass(), and HaloProperties().
unsigned HaloProperties::m_nPart [protected]
Definition at line 53 of file HaloProperties.h.
Referenced by AverageVel(), CenterOnCM(), CenterOnCMExc(), CenterOnCoord(), CenterOnMB(), CenterVel(), CenterVelExc(), CenterVelOn(), CleanUnbound(), CleanUnboundExc(), CleanUnboundSimple(), ComputeAngularMomentum(), ComputeCenterVel(), ComputeCenterVelExc(), ComputeCM(), ComputeCMExc(), ComputeDensityProfile(), ComputeKineticEnergy(), ComputeKineticEnergyNoHubble(), ComputeKineticEnergyNoHubbleExc(), ComputeLambdaPrime(), ComputeMajorAxes(), ComputeMajorAxesReduced(), ComputeMB(), ComputeMBExc(), ComputePotentialDirect(), ComputePotentialDirectExc(), ComputePotentialTree(), ComputePotentialTreeExc(), ComputeTotalMassExc(), ComputeVelocityDispersion(), GetSortedDistances(), and HaloProperties().
real * HaloProperties::m_pMass [protected]
Definition at line 51 of file HaloProperties.h.
Referenced by AverageVel(), CenterOnCM(), CenterOnCMExc(), CenterVel(), CenterVelExc(), ComputeAngularMomentum(), ComputeCenterVel(), ComputeCenterVelExc(), ComputeCM(), ComputeCMExc(), ComputeDensityProfile(), ComputeKineticEnergy(), ComputeKineticEnergyNoHubble(), ComputeKineticEnergyNoHubbleExc(), ComputeLambdaPrime(), ComputeMajorAxes(), ComputeMajorAxesReduced(), ComputePotentialDirect(), ComputePotentialDirectExc(), ComputePotentialTree(), ComputePotentialTreeExc(), ComputeTotalMassExc(), ComputeVirialProperties(), ComputeVirialProperties200(), and HaloProperties().
real* HaloProperties::m_pPos [protected]
Definition at line 51 of file HaloProperties.h.
Referenced by AverageVel(), CenterOnCM(), CenterOnCMExc(), CenterOnCoord(), CenterOnMB(), ComputeAngularMomentum(), ComputeCM(), ComputeCMExc(), ComputeKineticEnergy(), ComputeLambdaPrime(), ComputeMajorAxes(), ComputeMajorAxesReduced(), ComputeMB(), ComputeMBExc(), ComputePotentialDirect(), ComputePotentialDirectExc(), ComputePotentialTree(), ComputePotentialTreeExc(), GetSortedDistances(), and HaloProperties().
real * HaloProperties::m_pVel [protected]
Definition at line 51 of file HaloProperties.h.
Referenced by AverageVel(), CenterVel(), CenterVelExc(), CenterVelOn(), ComputeAngularMomentum(), ComputeCenterVel(), ComputeCenterVelExc(), ComputeKineticEnergy(), ComputeKineticEnergyNoHubble(), ComputeKineticEnergyNoHubbleExc(), ComputeLambdaPrime(), ComputeVelocityDispersion(), and HaloProperties().
real HaloProperties::m_rmbcm [protected]
Definition at line 50 of file HaloProperties.h.
Referenced by CenterOnMB().
real HaloProperties::m_vcm[3] [protected]
Definition at line 49 of file HaloProperties.h.
Referenced by CenterVel(), CenterVelExc(), CenterVelOn(), ComputeCenterVel(), and HaloProperties().
real HaloProperties::m_vmb[3] [protected]
Definition at line 49 of file HaloProperties.h.
Referenced by HaloProperties().
real HaloProperties::m_xcm[3] [protected]
Definition at line 49 of file HaloProperties.h.
Referenced by CenterOnCM(), CenterOnCMExc(), and HaloProperties().
real HaloProperties::m_xmb[3] [protected]
Definition at line 49 of file HaloProperties.h.
Referenced by CenterOnMB(), and HaloProperties().
The documentation for this class was generated from the following files:
HaloProperties.h
HaloProperties.cpp