Eigensystem3 Class Reference
#include <Eigensystem3.h>
Public Member Functions
Eigensystem3 ()
Eigensystem3 (Matrix33 M)
Eigensystem3 (const Eigensystem3 &E)
Eigensystem3 (std::vector< real > Eval, std::vector< Vector3 > Evec)
bool getEigen ()
std::vector< real > getEval () const
void setEval (std::vector< real > Eval)
real getEval (int index) const
std::vector< Vector3 > getEvec () const
void setEvec (std::vector< Vector3 > Evec)
Vector3 getEvec (int index) const
void calcEV ()
void normalize (real factor)
std::string toString (void)
Detailed Description
Definition at line 35 of file Eigensystem3.h.
Constructor & Destructor Documentation
Eigensystem3::Eigensystem3 ()
Definition at line 34 of file Eigensystem3.cpp.
Eigensystem3::Eigensystem3 (Matrix33 M)
Definition at line 38 of file Eigensystem3.cpp.
Eigensystem3::Eigensystem3 (const Eigensystem3 & E)
Definition at line 47 of file Eigensystem3.cpp.
Eigensystem3::Eigensystem3 (std::vector< real > Eval, std::vector< Vector3 > Evec)
Definition at line 51 of file Eigensystem3.cpp.
Member Function Documentation
void Eigensystem3::calcEV ()
Definition at line 58 of file Eigensystem3.cpp.
References Matrix33::Eigen().
Referenced by Halo::calcShape().
bool Eigensystem3::getEigen ()
real Eigensystem3::getEval (int index) const
Definition at line 76 of file Eigensystem3.cpp.
std::vector< real > Eigensystem3::getEval () const
Definition at line 70 of file Eigensystem3.cpp.
Referenced by AnalyzeSnap(), and StoreTensorField().
Vector3 Eigensystem3::getEvec (int index) const
Definition at line 93 of file Eigensystem3.cpp.
std::vector< Vector3 > Eigensystem3::getEvec () const
Definition at line 87 of file Eigensystem3.cpp.
Referenced by StoreTensorField().
void Eigensystem3::normalize (real factor)
Definition at line 104 of file Eigensystem3.cpp.
Referenced by Halo::calcShape().
void Eigensystem3::setEval (std::vector< real > Eval)
Definition at line 82 of file Eigensystem3.cpp.
void Eigensystem3::setEvec (std::vector< Vector3 > Evec)
Definition at line 99 of file Eigensystem3.cpp.
std::string Eigensystem3::toString (void)
Definition at line 120 of file Eigensystem3.cpp.
Referenced by HResults::toString(), and AResults::toString().
The documentation for this class was generated from the following files:
Eigensystem3.h
Eigensystem3.cpp