PoissonSolver< nstencil > Class Template Reference
#include <PoissonSolver.h>
Public Member Functions
PoissonSolver (ScalarField *prho, ScalarField *pphi)
double Gauss3D (const double &k, const double &sigma)
Gaussian kernel.
double TopHat3D (const double &k, const double &R)
void test ()
void solve (double Boxlength, double sigma)
PoissonSolver (ScalarField *prho)
double Gauss3D (const double &k, const double &sigma)
double TopHat3D (const double &k, const double &R)
void solve (ScalarField *pphi, double Boxlength, double sigma)
Protected Attributes
ScalarField * prho_
ScalarField * pphi_
ScalarField * m_prho
Detailed Description
template<int nstencil> class PoissonSolver< nstencil >
implementation of Poisson equation solver using Fourier transformation of the cloud-in-cell density field, templated for the number of stencils
Definition at line 52 of file PoissonSolver.h.
Constructor & Destructor Documentation
template<int nstencil> PoissonSolver< nstencil >::PoissonSolver (ScalarField * prho, ScalarField * pphi) [inline]
Definition at line 58 of file PoissonSolver.h.
References PoissonSolver< nstencil >::pphi_, and PoissonSolver< nstencil >::prho_.
template<int nstencil> PoissonSolver< nstencil >::PoissonSolver (ScalarField * prho) [inline]
Definition at line 60 of file PoissonSolver_new.h.
Member Function Documentation
template<int nstencil> double PoissonSolver< nstencil >::Gauss3D (const double & k, const double & sigma) [inline]
Definition at line 63 of file PoissonSolver_new.h.
template<int nstencil> double PoissonSolver< nstencil >::Gauss3D (const double & k, const double & sigma) [inline]
Gaussian kernel.
Definition at line 64 of file PoissonSolver.h.
Referenced by PoissonSolver< nstencil >::solve().
template<int nstencil> void PoissonSolver< nstencil >::solve (ScalarField * pphi, double Boxlength, double sigma) [inline]
Definition at line 79 of file PoissonSolver_new.h.
References ACC_C, ACC_R, c_im, c_re, PoissonSolver< nstencil >::Gauss3D(), PoissonSolver< nstencil >::m_prho, ScalarField::recreate(), and PoissonSolver< nstencil >::TopHat3D().
template<int nstencil> void PoissonSolver< nstencil >::solve (double Boxlength, double sigma) [inline]
invoke solver
Definition at line 101 of file PoissonSolver.h.
References ACC_C, ACC_R, GreensFunction< nOrder >::apply(), fftw_real, PoissonSolver< nstencil >::Gauss3D(), ScalarField::getNx(), ScalarField::getNy(), ScalarField::getNz(), ScalarField::getValue(), ofs, PoissonSolver< nstencil >::pphi_, PoissonSolver< nstencil >::prho_, ScalarField::setValue(), and PoissonSolver< nstencil >::TopHat3D().
Referenced by TidalField().
template<int nstencil> void PoissonSolver< nstencil >::test () [inline]
little test routine for access to prho_ and pphi_
Definition at line 85 of file PoissonSolver.h.
References ScalarField::getValue(), PoissonSolver< nstencil >::pphi_, PoissonSolver< nstencil >::prho_, and ScalarField::setValue().
Referenced by main().
template<int nstencil> double PoissonSolver< nstencil >::TopHat3D (const double & k, const double & R) [inline]
Definition at line 69 of file PoissonSolver_new.h.
template<int nstencil> double PoissonSolver< nstencil >::TopHat3D (const double & k, const double & R) [inline]
top hat kernel: all points inside radius R are fully accounted for, all points outside are not
Definition at line 74 of file PoissonSolver.h.
Referenced by PoissonSolver< nstencil >::solve().
Field Documentation
template<int nstencil> ScalarField* PoissonSolver< nstencil >::m_prho [protected]
Definition at line 57 of file PoissonSolver_new.h.
Referenced by PoissonSolver< nstencil >::solve().
template<int nstencil> ScalarField* PoissonSolver< nstencil >::pphi_ [protected]
Definition at line 55 of file PoissonSolver.h.
Referenced by PoissonSolver< nstencil >::PoissonSolver(), PoissonSolver< nstencil >::solve(), and PoissonSolver< nstencil >::test().
template<int nstencil> ScalarField* PoissonSolver< nstencil >::prho_ [protected]
Definition at line 54 of file PoissonSolver.h.
Referenced by PoissonSolver< nstencil >::PoissonSolver(), PoissonSolver< nstencil >::solve(), and PoissonSolver< nstencil >::test().
The documentation for this class was generated from the following files:
PoissonSolver.h
PoissonSolver_new.h