ExtractSnap.h File Reference
All publicly known functions of ExtractSnap.cpp.
Functions
void ExtractSnap (unsigned isnap)
Detailed Description
All publicly known functions of ExtractSnap.cpp.
Definition in file ExtractSnap.h.
Function Documentation
void ExtractSnap (unsigned isnap)
analysis of one single snapshot file
Parameters
isnap ID of snapshot formatted as a string of the form `XXX`
Returns
error code
Definition at line 42 of file ExtractSnap.cpp.
References DEBUG, donedebug(), Folder(), get_particle_number(), HDFCreateFile(), HDFCreateGroup(), HDFWriteDataset(), HDFWriteDatasetVector(), HDFWriteGroupAttribute(), read_gadget_1(), read_gadget_3(), RunCommand(), Snaps(), writedebug(), writedone(), writeln(), and writelndebug().
Referenced by main().