ExtractSnap.cpp File Reference
Reads out a Gadget2 snapshot file and stores the values in HDF5.
#include <fstream>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>
#include `HDFIO.h`
#include `ReadGadget.h`
#include `Global.h`
Functions
void ExtractSnap (unsigned isnap)
Detailed Description
Reads out a Gadget2 snapshot file and stores the values in HDF5.
Definition in file ExtractSnap.cpp.
Function Documentation
void ExtractSnap (unsigned isnap)
analysis of one single snapshot file
Parameters
isnap ID of snapshot formatted as a string of the form `XXX`
Returns
error code
Definition at line 42 of file ExtractSnap.cpp.
References DEBUG, donedebug(), Folder(), get_particle_number(), HDFCreateFile(), HDFCreateGroup(), HDFWriteDataset(), HDFWriteDatasetVector(), HDFWriteGroupAttribute(), read_gadget_1(), read_gadget_3(), RunCommand(), Snaps(), writedebug(), writedone(), writeln(), and writelndebug().
Referenced by main().