Global.h File Reference
All publicly known functions from Global.cpp.
#include <string>
#include <iostream>
Typedefs
typedef float real
Functions
void RunCommand (std::string command)
void write (std::string text)
void writedebug (bool DebugLevelActivated, std::string text)
void writeln (std::string text)
void writelndebug (bool DebugLevelActivated, std::string text)
void writedone (void)
void writelndone (void)
void donedebug (bool DebugLevelActivated)
std::string IntToString (int intValue)
std::string Folder (std::string where)
std::string Snaps (unsigned SnapNo)
bool DoesFileExist (char *filename)
unsigned GetLineNumber (std::string filename)
void printMinMaxValues (void)
print characteristics of basic types Show Minimum, Maximum, Sign, Bits, Inf for bool, char, int, long, unsigned, unsigned long, float, double
real fbmod (real x, real y)
template<typename real_t >
real_t SPHK3D (const real_t r, const real_t h)
Variables
const bool DEBUG = true
const double PI = 3.14159265358979323846264338327950288419716939937510582
Detailed Description
All publicly known functions from Global.cpp.
Definition in file Global.h.
Typedef Documentation
typedef float real
Definition at line 40 of file Global.h.
Function Documentation
bool DoesFileExist (char * filename)
Definition at line 40 of file Global.cpp.
Referenced by AssertFileOpen().
void donedebug (bool DebugLevelActivated)
Definition at line 143 of file Global.cpp.
References writelndone().
Referenced by CreateAHFParameterFile(), ExtractSnap(), GetMtreeFile(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RewriteParticleNumbers(), RunAHFstep(), RunOwnMergerTree(), SubhaloMatch(), WrapperParticleNumbers(), and WriteMtree2File().
real fbmod (real x, real y) [inline]
Definition at line 319 of file Global.cpp.
std::string Folder (std::string where)
Returns the paths to all important folders.
Parameters
where,: which folder? allowed: amd, snap, amateur, output, parameters
Returns
std::string full path
Definition at line 262 of file Global.cpp.
Referenced by AnalyzeSnap(), CreateAHFParameterFile(), CreateHaloTrackerParameterFile(), CreateMergeParameterFile(), ExtractSnap(), Output::getAR(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), openParticlesFile(), readDataBlocks(), RenameAHFout(), RewriteParticleNumbers(), RunAHFstep(), RunHaloTracker(), RunMergerTree(), RunOwnMergerTree(), SubhaloMatch(), TidalField(), WrapperParticleNumbers(), Output::writeAR(), Output::writeHR(), and Output::writeHRstripped().
unsigned GetLineNumber (std::string filename)
count the lines of a given file
Parameters
filename,: path to the file
Returns
unsigned number of lines
Definition at line 184 of file Global.cpp.
Referenced by SubhaloMatch().
std::string IntToString (int intValue)
Convert an integer into a string.
Parameters
intValue,: integer to be converted
Returns
std::string of that integer value
Definition at line 243 of file Global.cpp.
References itoa().
Referenced by TidalField().
void printMinMaxValues (void)
print characteristics of basic types Show Minimum, Maximum, Sign, Bits, Inf for bool, char, int, long, unsigned, unsigned long, float, double
Returns
: void
Definition at line 55 of file Global.cpp.
void RunCommand (std::string command)
Definition at line 174 of file Global.cpp.
Referenced by ExtractSnap(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RunAHFstep(), RunHaloTracker(), and RunMergerTree().
std::string Snaps (unsigned SnapNo)
Returns the full path to an AMATEUR snapshot
Parameters
SnapNo,: ID of snapshot
Returns
std::string full_path
Definition at line 291 of file Global.cpp.
Referenced by AnalyzeSnap(), CreateAHFParameterFile(), CreateHaloTrackerParameterFile(), CreateMergeParameterFile(), ExtractSnap(), Output::getAR(), HelpUser(), main(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), openParticlesFile(), readDataBlocks(), RenameAHFout(), RewriteParticleNumbers(), RunAHFstep(), RunOwnMergerTree(), SubhaloMatch(), TidalField(), WrapperParticleNumbers(), Output::writeAR(), Output::writeHR(), and Output::writeHRstripped().
template<typename real_t > real_t SPHK3D (const real_t r, const real_t h) [inline]
Definition at line 325 of file Global.cpp.
References PI.
Referenced by HaloProperties::AverageVel().
void write (std::string text)
Definition at line 110 of file Global.cpp.
Referenced by TidalField(), and writedebug().
void writedebug (bool DebugLevelActivated, std::string text)
Definition at line 154 of file Global.cpp.
References write().
Referenced by CreateAHFParameterFile(), ExtractSnap(), GetMtreeFile(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RewriteParticleNumbers(), RunOwnMergerTree(), SubhaloMatch(), WrapperParticleNumbers(), and WriteMtree2File().
void writedone (void)
Definition at line 127 of file Global.cpp.
Referenced by CreateHaloTrackerParameterFile(), CreateMergeParameterFile(), ExtractSnap(), and TidalField().
void writeln (std::string text)
Definition at line 119 of file Global.cpp.
Referenced by AnalyzeSnap(), ExtractSnap(), HelpUser(), main(), and writelndebug().
void writelndebug (bool DebugLevelActivated, std::string text)
Definition at line 165 of file Global.cpp.
References writeln().
Referenced by AnalyzeSnap(), ExtractSnap(), RunAHFstep(), RunHaloTracker(), RunMergerTree(), and RunOwnMergerTree().
void writelndone (void)
Definition at line 135 of file Global.cpp.
Referenced by donedebug(), and TidalField().
Variable Documentation
const bool DEBUG = true
Definition at line 36 of file Global.h.
Referenced by AnalyzeSnap(), CreateAHFParameterFile(), ExtractSnap(), GetMtreeFile(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RewriteParticleNumbers(), RunAHFstep(), RunHaloTracker(), RunMergerTree(), RunOwnMergerTree(), SubhaloMatch(), WrapperParticleNumbers(), and WriteMtree2File().
const double PI = 3.14159265358979323846264338327950288419716939937510582
Definition at line 37 of file Global.h.
Referenced by SPHK3D().