HaloTrackerRun.cpp File Reference
Implementation of -h, EXPERIMENTAL!
#include <fstream>
#include <iostream>
#include <string>
#include `Global.h`
Functions
void WrapperParticleNumbers (unsigned isnap)
void CreateHaloTrackerParameterFile (unsigned isnap)
void RunHaloTracker (void)
void MoveHaloTrackerOutput (unsigned isnap)
void HaloTrackerRun (unsigned isnap)
Detailed Description
Implementation of -h, EXPERIMENTAL!
Definition in file HaloTrackerRun.cpp.
Function Documentation
void CreateHaloTrackerParameterFile (unsigned isnap)
Definition at line 63 of file HaloTrackerRun.cpp.
References Folder(), Snaps(), and writedone().
Referenced by HaloTrackerRun().
void HaloTrackerRun (unsigned isnap)
Definition at line 95 of file HaloTrackerRun.cpp.
References CreateHaloTrackerParameterFile(), MoveHaloTrackerOutput(), RunHaloTracker(), and WrapperParticleNumbers().
void MoveHaloTrackerOutput (unsigned isnap)
Definition at line 87 of file HaloTrackerRun.cpp.
References DEBUG, donedebug(), Folder(), RunCommand(), Snaps(), and writedebug().
Referenced by HaloTrackerRun().
void RunHaloTracker (void)
Definition at line 78 of file HaloTrackerRun.cpp.
References DEBUG, Folder(), RunCommand(), and writelndebug().
Referenced by HaloTrackerRun().
void WrapperParticleNumbers (unsigned isnap)
Definition at line 32 of file HaloTrackerRun.cpp.
References DEBUG, donedebug(), Folder(), Snaps(), and writedebug().
Referenced by HaloTrackerRun().