MergerTreeRun.cpp File Reference
Rewrite of MergerTree of AMIGA, implements -m of amateur.
#include <fstream>
#include <iostream>
#include <string>
#include `Global.h`
#include <map>
Functions
void RewriteParticleNumbers (unsigned isnap)
void CreateMergeParameterFile (unsigned isnap)
void RunMergerTree (void)
void RunOwnMergerTree (int isnap)
void MoveMergeOut (unsigned isnap)
void MergerTreeRun (unsigned isnap)
Detailed Description
Rewrite of MergerTree of AMIGA, implements -m of amateur.
Definition in file MergerTreeRun.cpp.
Function Documentation
void CreateMergeParameterFile (unsigned isnap)
Definition at line 65 of file MergerTreeRun.cpp.
References Folder(), Snaps(), and writedone().
void MergerTreeRun (unsigned isnap)
Definition at line 192 of file MergerTreeRun.cpp.
References RunOwnMergerTree().
Referenced by main().
void MoveMergeOut (unsigned isnap)
Definition at line 184 of file MergerTreeRun.cpp.
References DEBUG, donedebug(), Folder(), RunCommand(), Snaps(), and writedebug().
void RewriteParticleNumbers (unsigned isnap)
Definition at line 31 of file MergerTreeRun.cpp.
References DEBUG, donedebug(), Folder(), Snaps(), and writedebug().
void RunMergerTree (void)
Definition at line 85 of file MergerTreeRun.cpp.
References DEBUG, Folder(), RunCommand(), and writelndebug().
void RunOwnMergerTree (int isnap)
Definition at line 97 of file MergerTreeRun.cpp.
References DEBUG, donedebug(), Folder(), Snaps(), writedebug(), and writelndebug().
Referenced by MergerTreeRun().