ReadGadget.c File Reference
sample input file from Gadget2, modified for use with AMATEUR
#include <iostream>
#include <string>
#include <string.h>
#include <cstdlib>
#include <stdio.h>
#include <stdlib.h>
Defines
#define SKIP {my_fread(&blksize,sizeof(int),1,fd); swap_Nbyte((char*)&blksize,1,sizeof(int));}
Functions
size_t my_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
void swap_Nbyte (char *data, unsigned n, unsigned m)
int find_block (FILE *fd, std::string label)
int read_gadget_head (unsigned *npart, double *Massarr, double *time, double *redshift, int *FlagSfr, int *FlagFeedback, unsigned *Nall, int *FlagCooling, int *NumFiles, double *BoxSize, FILE *fd)
template<typename T >
int read_gadget_1 (T *data, std::string label, FILE *fd)
template<typename T >
int read_gadget_3 (T *data, std::string label, FILE *fd)
void get_particle_number (std::string filename, unsigned *id_min, unsigned *id_max, double *masses, unsigned *npart, unsigned &ntot, double &redshift, double &boxsize)
template int read_gadget_1< float > (float *data, std::string label, FILE *fd)
template int read_gadget_1< unsigned > (unsigned *data, std::string label, FILE *fd)
template int read_gadget_1< int > (int *data, std::string label, FILE *fd)
template int read_gadget_3< float > (float *data, std::string label, FILE *fd)
Variables
int blksize
int swap_rg = 0
Detailed Description
sample input file from Gadget2, modified for use with AMATEUR
Definition in file ReadGadget.c.
Define Documentation
#define SKIP {my_fread(&blksize,sizeof(int),1,fd); swap_Nbyte((char*)&blksize,1,sizeof(int));}
Definition at line 20 of file ReadGadget.c.
Referenced by find_block(), read_gadget_1(), read_gadget_3(), and read_gadget_head().
Function Documentation
int find_block (FILE * fd, std::string label)
find a block in snapshot file
Parameters
fd
label
Returns
Definition at line 66 of file ReadGadget.c.
References blksize, my_fread(), SKIP, swap_Nbyte(), and swap_rg.
Referenced by read_gadget_1(), read_gadget_3(), and read_gadget_head().
void get_particle_number (std::string filename, unsigned * id_min, unsigned * id_max, double * masses, unsigned * npart, unsigned & ntot, double & redshift, double & boxsize)
Definition at line 220 of file ReadGadget.c.
References read_gadget_1(), and read_gadget_head().
Referenced by AnalyzeSnap(), and ExtractSnap().
size_t my_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 31 of file ReadGadget.c.
Referenced by find_block(), read_gadget_1(), read_gadget_3(), and read_gadget_head().
template<typename T > int read_gadget_1 (T * data, std::string label, FILE * fd) [inline]
read a 1D array
Parameters
data
label
fd
Returns
Definition at line 161 of file ReadGadget.c.
References find_block(), my_fread(), SKIP, and swap_Nbyte().
Referenced by ExtractSnap(), get_particle_number(), and readDataBlocks().
template int read_gadget_1< float > (float * data, std::string label, FILE * fd)
template int read_gadget_1< int > (int * data, std::string label, FILE * fd)
template int read_gadget_1< unsigned > (unsigned * data, std::string label, FILE * fd)
template<typename T > int read_gadget_3 (T * data, std::string label, FILE * fd) [inline]
read a 3D array
Parameters
data
label
fd
Returns
Definition at line 190 of file ReadGadget.c.
References find_block(), my_fread(), SKIP, and swap_Nbyte().
Referenced by ExtractSnap(), and readDataBlocks().
template int read_gadget_3< float > (float * data, std::string label, FILE * fd)
int read_gadget_head (unsigned * npart, double * Massarr, double * time, double * redshift, int * FlagSfr, int * FlagFeedback, unsigned * Nall, int * FlagCooling, int * NumFiles, double * BoxSize, FILE * fd)
read gadget header info
Parameters
npart
Massarr
time
redshift
FlagSfr
FlagFeedback
Nall
FlagCooling
NumFiles
BoxSize
fd
Returns
size of header block
Definition at line 115 of file ReadGadget.c.
References find_block(), my_fread(), SKIP, and swap_Nbyte().
Referenced by get_particle_number().
void swap_Nbyte (char * data, unsigned n, unsigned m)
swap endian
Parameters
data
n how many entries do we have in array?
m how many bytes are there for a bigger number type
Definition at line 47 of file ReadGadget.c.
References swap_rg.
Referenced by find_block(), read_gadget_1(), read_gadget_3(), and read_gadget_head().
Variable Documentation
int blksize
Definition at line 19 of file ReadGadget.c.
Referenced by find_block().
int swap_rg = 0
Definition at line 19 of file ReadGadget.c.
Referenced by find_block(), and swap_Nbyte().