SubhaloMatch.cpp File Reference
This file provides a wrapper to convert mtree_idx files generated by an autocorrelation run of AMIGA to give the host halo.
#include <string>
#include <iostream>
#include <map>
#include <fstream>
#include `Global.h`
Functions
void GetMtreeFile (std::string filename, int dim, unsigned *hostno, unsigned *hostpop, unsigned *sharedpop, unsigned *subno, unsigned *subpop)
void WriteMtree2File (std::string filename, int dim, unsigned *hostno, unsigned *hostpop, unsigned *sharedpop, unsigned *subno, unsigned *subpop)
void SubhaloMatch (unsigned isnap)
Detailed Description
This file provides a wrapper to convert mtree_idx files generated by an autocorrelation run of AMIGA to give the host halo.
Definition in file SubhaloMatch.cpp.
Function Documentation
void GetMtreeFile (std::string filename, int dim, unsigned * hostno, unsigned * hostpop, unsigned * sharedpop, unsigned * subno, unsigned * subpop)
Definition at line 32 of file SubhaloMatch.cpp.
References DEBUG, donedebug(), and writedebug().
Referenced by SubhaloMatch().
void SubhaloMatch (unsigned isnap)
Definition at line 61 of file SubhaloMatch.cpp.
References DEBUG, donedebug(), Folder(), GetLineNumber(), GetMtreeFile(), Snaps(), writedebug(), and WriteMtree2File().
Referenced by main().
void WriteMtree2File (std::string filename, int dim, unsigned * hostno, unsigned * hostpop, unsigned * sharedpop, unsigned * subno, unsigned * subpop)
Definition at line 46 of file SubhaloMatch.cpp.
References DEBUG, donedebug(), and writedebug().
Referenced by SubhaloMatch().