TidalField.cpp File Reference
Implements -t option: Computation of the tidal field.
#include <unistd.h>
#include <sstream>
#include `TidalField.h`
#include `HDFIO.h`
#include `PoissonSolver.h`
#include `Eigensystem3.h`
#include `Global.h`
Functions
void TidalField (unsigned isnap, int N, double Radius)
void TidalField (std::string snaphdf5, unsigned N, double Radius, std::string extra, std::string tensorhdf5)
Computes the tidal field from a given mass distribution.
void StoreTensorField (std::string filename, unsigned nPoints, const std::vector< float > &coordinates, const std::vector< Matrix33 > &aTensorField, float SmoothingMassScale)
Store tensor field. store tensor field to HDF5.
Variables
const float G_const = 43011.7902
Detailed Description
Implements -t option: Computation of the tidal field.
Definition in file TidalField.cpp.
Function Documentation
void StoreTensorField (std::string filename, unsigned nPoints, const std::vector< float > & coordinates, const std::vector< Matrix33 > & aTensorField, float SmoothingMassScale)
Store tensor field. store tensor field to HDF5.
Parameters
filename,: path to output file
nPoints,: number of points
coordinates,: evaluation points
aTensorField,: tensor field that should be evaluated
SmoothingMassScale,: smoothing scale
Definition at line 217 of file TidalField.cpp.
References Eigensystem3::getEval(), Eigensystem3::getEvec(), HDFWriteDataset2D(), and HDFWriteDatasetVector().
Referenced by TidalField().
void TidalField (std::string snaphdf5, unsigned N, double Radius, std::string extra, std::string tensorhdf5)
Computes the tidal field from a given mass distribution.
Parameters
snaphdf5,: a snapshot file, converted by AnalyzeSnap
N,: the length of the density mesh
Radius,: the length scale used for smoothing
extra,: file containing the -z output of the halos (used for npart, COM)
tensorhdf5,: output file for the tensor components
Returns
void
Definition at line 49 of file TidalField.cpp.
References ScalarField::diff2atCIC(), G_const, ScalarField::get_CIC(), HDFCreateFile(), HDFReadDataset(), HDFReadGroupAttribute(), HDFReadVector(), HDFWriteDataset(), ScalarField::put_CIC(), PoissonSolver< nstencil >::solve(), StoreTensorField(), write(), writedone(), and writelndone().
void TidalField (unsigned isnap, int N, double Radius)
Definition at line 25 of file TidalField.cpp.
References Folder(), IntToString(), Snaps(), and TidalField().
Referenced by main(), and TidalField().
Variable Documentation
const float G_const = 43011.7902
Definition at line 22 of file TidalField.cpp.
Referenced by TidalField().