#!/bin/bash
#PBS -S /bin/bash
#PBS -lnodes=1:cores16:ppn=16,walltime=00:00:05:00

# Copying program files to scratch

#module load mpi/impi

export RUNDIR=$TMPDIR

cd $TMPDIR
mkdir $TMPDIR/darcoda
mkdir $TMPDIR/darcoda/gravlite
mkdir $TMPDIR/darcoda/gravlite/programs

cp -r $HOME/LoDaM/darcoda/gravlite/programs/* $TMPDIR/darcoda/gravlite/programs/

cd $TMPDIR/darcoda/gravlite/programs

python3 gravlite.py

cp -r $TMPDIR/darcoda/gravlite/DTdiscmock/0/* $HOME/LoDaM/darcoda/gravlite/DTdiscmock/0/
