<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<title>Gravlite: Gravlite - Non-Parametric Mass Modelling Routine for Discs and Spheres</title>

<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css" />

<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { searchBox.OnSelectItem(0); });
</script>

</head>
<body>
<div id="top"><!-- do not remove this div! -->


<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  
  
  <td style="padding-left: 0.5em;">
   <div id="projectname">Gravlite
   
   </div>
   <div id="projectbrief">Mass modelling tool for spherical and disk-like structures</div>
  </td>
  
  
  
 </tr>
 </tbody>
</table>
</div>

<!-- Generated by Doxygen 1.7.6.1 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li class="current"><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<div class="title">Gravlite - Non-Parametric Mass Modelling Routine for Discs and Spheres </div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><h2><a class="anchor" id="intro_sec"></a>
Introduction</h2>
<p>Gravlite is a tool to determine the mass distribution in disc-like and spherical systems. It takes as input a tracer density distribution, a line-of-sight velocity dispersion, and the velocity's fourth moment as a function of radius. It then generates a highly-dimensional parameter space for tracer density, overall density distribution, and possibly a velocity anisotropy profile ands traces it with a simple Markov Chain Monte Carlo method.</p>
<h2><a class="anchor" id="install_sec"></a>
Installation</h2>
<p>Following packets need to be installed on your system: * python3 * matplotlib/pylab * scipy</p>
<p>Unzip the file gravlite.zip, and run</p>
<p>python3 <a class="el" href="gravlite_8py.html" title="main file">gravlite.py</a></p>
<h3><a class="anchor" id="pars"></a>
Parameter files: Main configuration</h3>
<p>Sample parameter files for several possible scenarios are stored in the subfolder ./params. The file <a class="el" href="gl__params_8py.html" title="all parameters for the gravlite MCMC, gaia investigation">gl_params.py</a> is a soft link to one of them. Following mass modelling methods have been implemented so far: * <a class="el" href="gl__params__walker_8py.html" title="parameters for the gravlite MCMC, working on the Walker datasets">gl_params_walker.py</a>: spherical Walker mock data from the Gaia challenge catalogue, 2 populations * <a class="el" href="gl__params__gaia_8py.html" title="all parameters for the gravlite MCMC, gaia investigation">gl_params_gaia.py</a>: spherical mock data from the Gaia challenge catalogue, 1 population * gl_params_hern.py: spherical mock data taken from a Hernquist profile * <a class="el" href="gl__params__simple_8py.html" title="parameters for the gravlite MCMC, working with disk-like structures generated on the fly...">gl_params_simple.py</a>: disk-like mock data, generated on the fly * <a class="el" href="gl__params__sim_8py.html" title="parameters for the gravlite MCMC, with mock disk structures">gl_params_sim.py</a>: disk-like mock data, from a simulation by S. Garbari</p>
<h3><a class="anchor" id="init"></a>
Init values</h3>
<p>Initial values for all profiles and the respective stepsizes are set in <a class="el" href="gl__init_8py.html" title="set up initial parameters">gl_init.py</a>. We use following representations: * overall density rho: can either be set as rho_i=rho(r_i), where r_i are the radii of bins, or the coefficients of the Legendre polynomial; * tracer densities nu_i = nu(r_i) in linear space or nu_i = log(nu(r_i)) in logarithmic space; * velocity anisotropy beta_i are incremental changes from beta(r=0) = 0.</p>
<p>Have fun! </p>
</div></div><!-- contents -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&#160;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&#160;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&#160;</span>Namespaces</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&#160;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&#160;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&#160;</span>Variables</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>



<hr class="footer"/><address class="footer"><small>
Generated on Wed Oct 23 2013 15:01:16 for Gravlite by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.7.6.1
</small></address>

</body>
</html>
